{
 "title": "NFS",
 "tags": [
  "NamedQueries",
  "protocols"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "system", "label": "cluster selection", "query": "opentsdb" },
   { "name": "byNode", "label": "filter byNode", "query": "tag_values(nfs_read, node)" },
   { "name": "byExport", "label": "filter byExport", "query": "tag_values(nfs_read, export)" }
  ]
 },
 "panels": [
  {
   "title": "NFS Errors",
   "type": "graph",
   "description": "get the NFS error count for read and write operations",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "noop",
     "alias": "read_err: $tag_export",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "filters": [
      {
       "filter": "$byExport",
       "groupBy": true,
       "tagk": "export",
       "type": "pm_filter"
      }
     ],
     "metric": "nfs_read_err"
    },
    {
     "aggregator": "noop",
     "alias": "write_err: $tag_export",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "filters": [
      {
       "filter": "$byExport",
       "groupBy": true,
       "tagk": "export",
       "type": "pm_filter"
      }
     ],
     "metric": "nfs_write_err"
    }
   ]
  },
  {
   "title": "NFS Queue",
   "type": "graph",
   "description": "get the NFS read and write queue size in bytes",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "noop",
     "alias": "read_queue: $tag_export",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "filters": [
      {
       "filter": "$byExport",
       "groupBy": true,
       "tagk": "export",
       "type": "pm_filter"
      }
     ],
     "metric": "nfs_read_queue"
    },
    {
     "aggregator": "noop",
     "alias": "write_queue: $tag_export",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "filters": [
      {
       "filter": "$byExport",
       "groupBy": true,
       "tagk": "export",
       "type": "pm_filter"
      }
     ],
     "metric": "nfs_write_queue"
    }
   ]
  },
  {
   "title": "NFS Throughput",
   "type": "graph",
   "description": "Display the NFS Throughput in bytes per second.\nCompare to the mmperfmon NamedQuery 'nfsThroughput' F.e. try on the command line:\n\n# mmperfmon query nfsThroughput 3600 -b 60",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "noop",
     "alias": "read: $tag_export",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "filters": [
      {
       "filter": "$byExport",
       "groupBy": true,
       "tagk": "export",
       "type": "pm_filter"
      }
     ],
     "metric": "nfs_read"
    },
    {
     "aggregator": "noop",
     "alias": "write: $tag_export",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "filters": [
      {
       "filter": "$byExport",
       "groupBy": true,
       "tagk": "export",
       "type": "pm_filter"
      }
     ],
     "metric": "nfs_write"
    }
   ]
  },
  {
   "title": "NFS IO Rate",
   "type": "graph",
   "description": "get the NFS IOps per second",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "noop",
     "alias": "readOPS: $tag_export",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "filters": [
      {
       "filter": "$byExport",
       "groupBy": true,
       "tagk": "export",
       "type": "pm_filter"
      }
     ],
     "metric": "nfs_read_ops"
    },
    {
     "aggregator": "noop",
     "alias": "writeOPS: $tag_export",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "filters": [
      {
       "filter": "$byExport",
       "groupBy": true,
       "tagk": "export",
       "type": "pm_filter"
      }
     ],
     "metric": "nfs_write_ops"
    }
   ]
  }
 ]
}