{
 "title": "Inodes Capacity View",
 "tags": [
  "default",
  "capacity"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "byCluster", "label": "select cluster", "query": "opentsdb" },
   { "name": "gpfsMetrics_inode", "label": "metric1", "query": "metrics(gpfs_fs_inode_)" },
   { "name": "gpfsMetrics", "label": "metric1", "query": "metrics(gpfs_fs.*)" },
   {
    "name": "byFsName",
    "label": "select filesystem",
    "query": "tag_values($gpfsMetrics,  gpfs_fs_name)"
   },
   {
    "name": "values",
    "label": "values",
    "query": "tag_values($gpfsMetrics, $filterBy)"
   },
   { "name": "gpfsMetrics_pool_cap", "label": "metric2", "query": "metrics(gpfs_pool_*)" },
   {
    "name": "byPoolName",
    "query": "tag_values($gpfsMetrics, gpfs_diskpool_name)"
   },
   {
    "name": "byDisk",
    "query": "tag_values($gpfsMetrics, gpfs_disk_name)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "\nOn this dashboard you can monitor filesystem inodes allocation and usage\n\n"
   },
   "content": "\nOn this dashboard you can monitor filesystem inodes allocation and usage\n\n"
  },
  {
   "title": "MAX inodes per Filesystem",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "noop",
     "alias": "\"filesystem: [[tag_gpfs_fs_name]]\"",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "",
       "groupBy": true,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_fs_inode_max"
    }
   ]
  },
  {
   "title": "\"$gpfsMetrics_inode\" (FILESYSTEMS)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "\"filesystem: [[tag_gpfs_fs_name]]\"",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "",
       "groupBy": true,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      }
     ],
     "metric": "$gpfsMetrics_inode"
    }
   ]
  },
  {
   "title": "inodes allocated/used by \"$byFsName\"",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "noop",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$byFsName",
       "groupBy": true,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_fs_inode_alloc"
    },
    {
     "aggregator": "noop",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$byFsName",
       "groupBy": true,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_fs_inode_used"
    }
   ]
  },
  {
   "title": "inodes usage by\"$byFsName\"",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "noop",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$byFsName",
       "groupBy": true,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_fs_inode_max"
    },
    {
     "aggregator": "noop",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$byFsName",
       "groupBy": true,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_fs_inode_used"
    }
   ]
  },
  {
   "title": "inodes allocated/free by  \"$byFsName\"",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "noop",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$byFsName",
       "groupBy": true,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_fs_inode_alloc"
    },
    {
     "aggregator": "noop",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$byFsName",
       "groupBy": true,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_fs_inode_free"
    }
   ]
  }
 ]
}