{
 "title": "AFM  FSET view",
 "tags": [
  "afm",
  "fileset"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "system", "label": "cacheCluster", "query": "opentsdb" },
   {
    "name": "gateWayNode",
    "label": "filter by Primary Gateway node",
    "query": "tag_values(gpfs_afm_fset_bytes_read, node)"
   },
   {
    "name": "afmFSET",
    "label": "filter by AFM Fileset",
    "query": "tag_values(gpfs_afm_fset_ops_sent, gpfs_fset_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "$afmFSET (number of bytes written)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "aggregator": "noop",
     "alias": "$tag_node",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$gateWayNode",
       "groupBy": false,
       "tagk": "node",
       "type": "pm_filter"
      },
      {
       "filter": "$afmFSET",
       "groupBy": false,
       "tagk": "gpfs_fset_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_afm_fset_bytes_written"
    }
   ]
  },
  {
   "title": " $afmFSET (number of operations sent )",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "aggregator": "noop",
     "alias": "$tag_node",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$gateWayNode",
       "groupBy": false,
       "tagk": "node",
       "type": "pm_filter"
      },
      {
       "filter": "$afmFSET",
       "groupBy": false,
       "tagk": "gpfs_fset_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_afm_fset_ops_sent"
    }
   ]
  },
  {
   "title": "$afmFSET (used memory in bytes by the messages queued)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "aggregator": "noop",
     "alias": "$tag_node",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$gateWayNode",
       "groupBy": false,
       "tagk": "node",
       "type": "pm_filter"
      },
      {
       "filter": "$afmFSET",
       "groupBy": false,
       "tagk": "gpfs_fset_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_afm_fset_used_q_memory"
    }
   ]
  },
  {
   "title": "$afmFSET (number of messages that are currently queued)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "aggregator": "noop",
     "alias": "$tag_node",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$gateWayNode",
       "groupBy": false,
       "tagk": "node",
       "type": "pm_filter"
      },
      {
       "filter": "$afmFSET",
       "groupBy": false,
       "tagk": "gpfs_fset_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_afm_fset_num_queued_msgs"
    }
   ]
  },
  {
   "title": "TREND CHARTS - Total number of bytes read/write from/to remote system  for \"$afmFSET\" ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total number of bytes read",
     "type": "stat",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "aggregator": "sum",
       "downsampleAggregator": "noop",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "$gateWayNode",
         "groupBy": false,
         "tagk": "node",
         "type": "pm_filter"
        },
        {
         "filter": "$afmFSET",
         "groupBy": false,
         "tagk": "gpfs_fset_name",
         "type": "pm_filter"
        }
       ],
       "metric": "gpfs_afm_fset_bytes_read"
      }
     ]
    },
    {
     "title": "Total number of bytes written",
     "type": "stat",
     "gridPos": { "h": 7, "w": 7, "x": 7, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "aggregator": "sum",
       "downsampleAggregator": "noop",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "$gateWayNode",
         "groupBy": false,
         "tagk": "node",
         "type": "pm_filter"
        },
        {
         "filter": "$afmFSET",
         "groupBy": false,
         "tagk": "gpfs_fset_name",
         "type": "pm_filter"
        }
       ],
       "metric": "gpfs_afm_fset_bytes_written"
      }
     ]
    },
    {
     "title": "Total number of bytes  pending",
     "type": "stat",
     "gridPos": { "h": 7, "w": 7, "x": 14, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "aggregator": "sum",
       "downsampleAggregator": "noop",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "$gateWayNode",
         "groupBy": false,
         "tagk": "node",
         "type": "pm_filter"
        },
        {
         "filter": "$afmFSET",
         "groupBy": false,
         "tagk": "gpfs_fset_name",
         "type": "pm_filter"
        }
       ],
       "metric": "gpfs_afm_fset_bytes_pending"
      }
     ]
    }
   ]
  },
  {
   "title": "TREND CHARTS - Number of operations that were sent to remote system for \"$afmFSET\" ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "repeat": "afmFSET",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": " Total number of operations sent ",
     "type": "stat",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "aggregator": "sum",
       "alias": "$tag_gpfs_fset_name",
       "downsampleAggregator": "noop",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "$gateWayNode",
         "groupBy": false,
         "tagk": "node",
         "type": "pm_filter"
        },
        {
         "filter": "$afmFSET",
         "groupBy": false,
         "tagk": "gpfs_fset_name",
         "type": "pm_filter"
        }
       ],
       "metric": "gpfs_afm_fset_ops_sent"
      }
     ]
    },
    {
     "title": " Total number of synchronous operations",
     "type": "stat",
     "gridPos": { "h": 7, "w": 7, "x": 7, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "aggregator": "sum",
       "downsampleAggregator": "noop",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "$gateWayNode",
         "groupBy": false,
         "tagk": "node",
         "type": "pm_filter"
        },
        {
         "filter": "$afmFSET",
         "groupBy": false,
         "tagk": "gpfs_fset_name",
         "type": "pm_filter"
        }
       ],
       "metric": "gpfs_afm_fset_ops_sync"
      }
     ]
    },
    {
     "title": " Total number of operations revoked ",
     "type": "stat",
     "gridPos": { "h": 7, "w": 7, "x": 14, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "aggregator": "sum",
       "downsampleAggregator": "noop",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "$gateWayNode",
         "groupBy": false,
         "tagk": "node",
         "type": "pm_filter"
        },
        {
         "filter": "$afmFSET",
         "groupBy": false,
         "tagk": "gpfs_fset_name",
         "type": "pm_filter"
        }
       ],
       "metric": "gpfs_afm_fset_ops_revoked"
      }
     ]
    }
   ]
  },
  {
   "title": "TREND CHARTS - Time in seconds that a pending operation waited in the gateway queue before being sent to remote system for \"$afmFSET \"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Average time in seconds",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "aggregator": "avg",
       "downsampleAggregator": "noop",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "$gateWayNode",
         "groupBy": false,
         "tagk": "node",
         "type": "pm_filter"
        },
        {
         "filter": "$afmFSET",
         "groupBy": false,
         "tagk": "gpfs_fset_name",
         "type": "pm_filter"
        }
       ],
       "metric": "gpfs_afm_fset_avg_time"
      }
     ]
    },
    {
     "title": "Longest time in seconds",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "aggregator": "max",
       "downsampleAggregator": "noop",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "$gateWayNode",
         "groupBy": false,
         "tagk": "node",
         "type": "pm_filter"
        },
        {
         "filter": "$afmFSET",
         "groupBy": false,
         "tagk": "gpfs_fset_name",
         "type": "pm_filter"
        }
       ],
       "metric": "gpfs_afm_fset_longest_time"
      }
     ]
    },
    {
     "title": "Shortest time in seconds",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "min" ] } },
     "targets": [
      {
       "aggregator": "min",
       "downsampleAggregator": "noop",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "$gateWayNode",
         "groupBy": false,
         "tagk": "node",
         "type": "pm_filter"
        },
        {
         "filter": "$afmFSET",
         "groupBy": false,
         "tagk": "gpfs_fset_name",
         "type": "pm_filter"
        }
       ],
       "metric": "gpfs_afm_fset_shortest_time"
      }
     ]
    }
   ]
  },
  {
   "title": "Total number of times the connection to the remote system was established/ broken for the \"$afmFSET \" fileset",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total number  a connection was established",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "aggregator": "max",
       "downsampleAggregator": "noop",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "$gateWayNode",
         "groupBy": false,
         "tagk": "node",
         "type": "pm_filter"
        },
        {
         "filter": "$afmFSET",
         "groupBy": false,
         "tagk": "gpfs_fset_name",
         "type": "pm_filter"
        }
       ],
       "metric": "gpfs_afm_fset_conn_esta"
      }
     ]
    },
    {
     "title": "Total number  a connection was broken",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "aggregator": "max",
       "downsampleAggregator": "noop",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "$gateWayNode",
         "groupBy": false,
         "tagk": "node",
         "type": "pm_filter"
        },
        {
         "filter": "$afmFSET",
         "groupBy": false,
         "tagk": "gpfs_fset_name",
         "type": "pm_filter"
        }
       ],
       "metric": "gpfs_afm_fs_conn_broken"
      }
     ]
    }
   ]
  }
 ]
}