{
 "title": "GPFS Cluster overview (Prometheus)",
 "tags": [
  "prometheus",
  "health",
  "overview"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "gridPos": { "h": 10, "w": 21, "x": 0, "y": 0 } },
  {
   "title": "Warning events ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gpfs_health_warning_events{gpfs_health_entity=\"-\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error events ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gpfs_health_error_events{gpfs_health_entity=\"-\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filesystems",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "sum by(gpfs_cluster_name, gpfs_fs_name) (gpfs_disk_disksize)",
     "legendFormat": "{{gpfs_fs_name}}"
    }
   ]
  },
  {
   "title": "Disk capacity usage by Filesystem",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($B-$A)/$B", "type": "math" }
   ]
  },
  {
   "title": "Filesystem MGR",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(node, gpfs_health_entity) (max_over_time(gpfs_health_status{gpfs_health_component=\"FILESYSMGR\", gpfs_health_entity!=\"-\"}[15m]))",
     "legendFormat": "{{gpfs_health_entity}}  on node {{node}}"
    }
   ]
  },
  {
   "title": "Filesystem READ OPS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(gpfs_cluster_name) (gpfs_fs_read_ops)",
     "legendFormat": "{{gpfs_cluster_name}}"
    }
   ]
  },
  {
   "title": "Used disks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "sum by(gpfs_cluster_name, gpfs_disk_name) (gpfs_disk_disksize)",
     "legendFormat": "{{gpfs_fs_name}}"
    }
   ]
  }
 ]
}