{
 "title": "Monitoring Filesystems",
 "tags": [ "filesystem" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Datenquelle", "label": "Datasource", "query": "opentsdb" },
   {
    "name": "byFsName",
    "query": "tag_values(gpfs_fs_disks, gpfs_fs_name)"
   },
   {
    "name": "byNode",
    "query": "tag_values(gpfs_fs_disks, node)"
   },
   { "name": "fsOpsMetric", "label": "ops metrics", "query": "metrics(gpfs_fs_.*)" },
   { "name": "fsTimeMetric", "label": "time metrics", "query": "metrics(gpfs_fs_.*)" },
   { "name": "fsBytesMetric", "label": "bytes metrics", "query": "metrics(gpfs_fs_.*)" }
  ]
 },
 "panels": [
  {
   "title": "Data/Bytes metrics example quries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "By selecting _bytes metrics_, you can switch between:\n\n - gpfs_fs_bytes_read: Number of bytes read.\n - gpfs_fs_bytes_written: Number of bytes written. \n\nFor more info please check [IBM Spectrum Scale Knowledge Center](https://www.ibm.com/docs/en/spectrum-scale/5.1.4?topic=metrics-gpfs#listofmetrics__section_gpfsfilesystem)"
     }
    },
    {
     "title": "\"$fsBytesMetric\" from \"$byNode\" node, \"$byFsName\" Filesystem of $Datenquelle",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "aggregator": "noop",
       "alias": "$tag_node",
       "downsampleAggregator": "noop",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "$byNode",
         "groupBy": false,
         "tagk": "node",
         "type": "pm_filter"
        },
        {
         "filter": "$byFsName",
         "groupBy": false,
         "tagk": "gpfs_fs_name",
         "type": "pm_filter"
        }
       ],
       "metric": "$fsBytesMetric"
      },
      {
       "aggregator": "sum",
       "alias": "summed up in $Datenquelle",
       "downsampleAggregator": "noop",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "$byFsName",
         "groupBy": false,
         "tagk": "gpfs_fs_name",
         "type": "pm_filter"
        }
       ],
       "metric": "$fsBytesMetric"
      }
     ]
    },
    {
     "title": "\"gpfs_fs_bytes_read\" from \"$byNode\" node, \"$byFsName\" Filesystem of $Datenquelle aggregated to 15 min values",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "aggregator": "noop",
       "alias": "$tag_node",
       "currentFilterType": "literal_or",
       "downsampleAggregator": "sum",
       "downsampleFillPolicy": "none",
       "downsampleInterval": "15m",
       "filters": [
        {
         "filter": "$byFsName",
         "groupBy": false,
         "tagk": "gpfs_fs_name",
         "type": "pm_filter"
        },
        {
         "filter": "$byNode",
         "groupBy": false,
         "tagk": "node",
         "type": "pm_filter"
        }
       ],
       "metric": "$fsBytesMetric"
      }
     ]
    }
   ]
  },
  {
   "title": "Operations/Number metrics example queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 2 },
     "options": {
      "content": "By selecting _ops metrics_, you can switch between:\n\n - gpfs_fs_read_ops: Number of read operations. \n - gpfs_fs_write_ops: Number of write operations.\n\nFor more info please check [IBM Spectrum Scale Knowledge Center](https://www.ibm.com/docs/en/spectrum-scale/5.1.4?topic=metrics-gpfs#listofmetrics__section_gpfsfilesystem)"
     }
    },
    {
     "title": "\"$fsOpsMetric\" from \"$byNode\" node,  \"$byFsName\"  Filesystem of $Datenquelle",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "aggregator": "noop",
       "alias": "$tag_node",
       "currentFilterType": "literal_or",
       "downsampleAggregator": "noop",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "$byFsName",
         "groupBy": false,
         "tagk": "gpfs_fs_name",
         "type": "pm_filter"
        },
        {
         "filter": "$byNode",
         "groupBy": false,
         "tagk": "node",
         "type": "pm_filter"
        }
       ],
       "metric": "$fsOpsMetric"
      },
      {
       "aggregator": "sum",
       "alias": "summiert in $Datenquelle",
       "currentTagKey": "node",
       "currentTagValue": "pm_filter()",
       "downsampleAggregator": "noop",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "$byFsName",
         "groupBy": false,
         "tagk": "gpfs_fs_name",
         "type": "pm_filter"
        }
       ],
       "metric": "$fsOpsMetric"
      }
     ]
    },
    {
     "title": "\"$fsOpsMetric\" from \"$byNode\" node, \"$byFsName\" Filesystem of $Datenquelle aggregated to 15 min values",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "aggregator": "noop",
       "alias": "$tag_node",
       "currentFilterType": "literal_or",
       "downsampleAggregator": "sum",
       "downsampleFillPolicy": "none",
       "downsampleInterval": "15m",
       "filters": [
        {
         "filter": "$byFsName",
         "groupBy": false,
         "tagk": "gpfs_fs_name",
         "type": "pm_filter"
        },
        {
         "filter": "$byNode",
         "groupBy": false,
         "tagk": "node",
         "type": "pm_filter"
        }
       ],
       "metric": "gpfs_fs_read_ops"
      }
     ]
    }
   ]
  },
  {
   "title": "Assess Time/Seconds metrics example queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
     "options": {
      "content": "By selecting _time metrics_, you can switch between:\n\n - gpfs_fs_max_disk_wait_rd: The longest time spent waiting for a disk read operation.\n - gpfs_fs_max_disk_wait_wr: The longest time spent waiting for a disk write operation.\n - gpfs_fs_max_queue_wait_rd: The longest time between being enqueued for a disk read operation and the completion of that operation.\n - gpfs_fs_max_queue_wait_wr: The longest time between being enqueued for a disk write operation and the completion of that operation.\n - gpfs_fs_min_disk_wait_rd: The shortest time spent waiting for a disk read operation.\n - gpfs_fs_min_disk_wait_wr: The shortest time spent waiting for a disk write operation.\n - gpfs_fs_min_queue_wait_rd: The shortest time between being enqueued for a disk read operation and the completion of that operation.\n - gpfs_fs_min_queue_wait_wr: The shortest time between being enqueued for a disk write operation and the completion of that operation.\n - gpfs_fs_tot_disk_wait_rd: The total time in seconds spent waiting for disk read operations.\n - gpfs_fs_tot_disk_wait_wr: The total time in seconds spent waiting for disk write operations.\n - gpfs_fs_tot_queue_wait_rd: The total time that is spent between being enqueued for a read operation and the completion of that operation.\n - gpfs_fs_tot_queue_wait_wr: The total time that is spent between being enqueued for a write operation and the completion of that operation.\n\n\n\nFor more info please check [IBM Spectrum Scale Knowledge Center](https://www.ibm.com/docs/en/spectrum-scale/5.1.4?topic=metrics-gpfs#listofmetrics__section_gpfsfilesystem)"
     }
    },
    {
     "title": "\"$fsTimeMetric\" from \"$byNode\" node, \"$byFsName\" Filesystem of $Datenquelle",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "aggregator": "noop",
       "alias": "$tag_node",
       "downsampleAggregator": "noop",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "$byFsName",
         "groupBy": false,
         "tagk": "gpfs_fs_name",
         "type": "pm_filter"
        },
        {
         "filter": "$byNode",
         "groupBy": false,
         "tagk": "node",
         "type": "pm_filter"
        }
       ],
       "metric": "$fsTimeMetric"
      },
      {
       "aggregator": "sum",
       "alias": "summiert in $Datenquelle",
       "downsampleAggregator": "noop",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "$byFsName",
         "groupBy": false,
         "tagk": "gpfs_fs_name",
         "type": "pm_filter"
        }
       ],
       "metric": "$fsTimeMetric"
      }
     ]
    },
    {
     "title": "\"$fsTimeMetric\" from \"$byNode\" node, \"$byFsName\"  Filesystem of $Datenquelle aggregated to 15 min values",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "aggregator": "noop",
       "alias": "$tag_node",
       "currentFilterType": "literal_or",
       "currentTagKey": "node",
       "currentTagValue": "pm_filter()",
       "downsampleAggregator": "noop",
       "downsampleFillPolicy": "none",
       "downsampleInterval": "15m",
       "filters": [
        {
         "filter": "$byFsName",
         "groupBy": false,
         "tagk": "gpfs_fs_name",
         "type": "pm_filter"
        },
        {
         "filter": "$byNode",
         "groupBy": false,
         "tagk": "node",
         "type": "pm_filter"
        }
       ],
       "metric": "$fsTimeMetric"
      }
     ]
    }
   ]
  }
 ]
}