{
 "title": "(Linux)Network and general metrics",
 "tags": [
  "linux",
  "network"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "system", "label": "Datasource", "query": "opentsdb" },
   { "name": "byNode", "label": "filter byNode", "query": "tag_values(cpu_user,node)" }
  ]
 },
 "panels": [
  {
   "title": "Usage",
   "type": "graph",
   "description": "show CPU, memory, storage and network usage",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "cpu_user" },
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "cpu_system" },
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "mem_memtotal" },
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "mem_memfree" },
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "df_free" },
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "df_total" },
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "df_used" }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "show CPU utilization in system and user space, and context switches",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "noop",
     "alias": "system: $tag_node",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "filters": [
      {
       "filter": "$byNode",
       "groupBy": true,
       "tagk": "node",
       "type": "pm_filter"
      }
     ],
     "metric": "cpu_system"
    },
    {
     "aggregator": "noop",
     "alias": "user: $tag_node",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "filters": [
      {
       "filter": "$byNode",
       "groupBy": true,
       "tagk": "node",
       "type": "pm_filter"
      }
     ],
     "metric": "cpu_user"
    },
    {
     "aggregator": "noop",
     "alias": "contexts: $tag_node",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "filters": [
      {
       "filter": "$byNode",
       "groupBy": true,
       "tagk": "node",
       "type": "pm_filter"
      }
     ],
     "metric": "cpu_contexts"
    }
   ]
  },
  {
   "title": "Network Problems",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "collisions",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "metric": "netdev_collisions"
    },
    {
     "aggregator": "avg",
     "alias": "drops_r",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "metric": "netdev_drops_r"
    },
    {
     "aggregator": "avg",
     "alias": "errors_r",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "metric": "netdev_errors_r"
    },
    {
     "aggregator": "avg",
     "alias": "errors_s",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "metric": "netdev_errors_s"
    }
   ]
  },
  {
   "title": "Network Details",
   "type": "graph",
   "description": "Get details about the network.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "aggregator": "noop",
     "alias": "bytes_r: $tag_node",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "filters": [
      {
       "filter": "lo",
       "groupBy": false,
       "tagk": "netdev_name",
       "type": "pm_filter"
      },
      {
       "filter": "$byNode",
       "groupBy": true,
       "tagk": "node",
       "type": "pm_filter"
      }
     ],
     "metric": "netdev_bytes_r"
    },
    {
     "aggregator": "noop",
     "alias": "bytes_s : $tag_node",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "filters": [
      {
       "filter": "lo",
       "groupBy": false,
       "tagk": "netdev_name",
       "type": "pm_filter"
      },
      {
       "filter": "$byNode",
       "groupBy": true,
       "tagk": "node",
       "type": "pm_filter"
      }
     ],
     "metric": "netdev_bytes_s"
    },
    {
     "aggregator": "noop",
     "alias": "collisions: $tag_node",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "filters": [
      {
       "filter": "lo",
       "groupBy": false,
       "tagk": "netdev_name",
       "type": "pm_filter"
      },
      {
       "filter": "$byNode",
       "groupBy": true,
       "tagk": "node",
       "type": "pm_filter"
      }
     ],
     "metric": "netdev_collisions"
    },
    {
     "aggregator": "noop",
     "alias": "carrier : $tag_node",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "filters": [
      {
       "filter": "lo",
       "groupBy": false,
       "tagk": "netdev_name",
       "type": "pm_filter"
      },
      {
       "filter": "$byNode",
       "groupBy": true,
       "tagk": "node",
       "type": "pm_filter"
      }
     ],
     "metric": "netdev_carrier"
    }
   ]
  }
 ]
}