{
 "title": "SMB operations",
 "tags": [
  "smb ",
  "protocols"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "byCluster", "label": "select cluster", "query": "opentsdb" },
   {
    "name": "byNode",
    "label": "select protocol node",
    "query": "tag_values(connect_count, node)"
   },
   {
    "name": "operation",
    "label": "select operation",
    "query": "tag_values(op_count, operation)"
   },
   {
    "name": "tInterval",
    "label": "t_interval",
    "query": "10s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "SMB latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "alias": "op_time",
     "downsampleAggregator": "max",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "$tInterval",
     "filters": [
      {
       "filter": "$byNode",
       "groupBy": false,
       "tagk": "node",
       "type": "pm_filter"
      },
      {
       "filter": "$operation",
       "groupBy": false,
       "tagk": "operation",
       "type": "pm_filter"
      }
     ],
     "metric": "op_time"
    },
    {
     "aggregator": "sum",
     "alias": "op_count",
     "downsampleAggregator": "max",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "$tInterval",
     "filters": [
      {
       "filter": "$byNode",
       "groupBy": false,
       "tagk": "node",
       "type": "pm_filter"
      },
      {
       "filter": "$operation",
       "groupBy": false,
       "tagk": "operation",
       "type": "pm_filter"
      }
     ],
     "metric": "op_count"
    }
   ]
  },
  {
   "title": "SMB 'op_count'   for node: $byNode",
   "type": "table-old",
   "gridPos": { "h": 18, "w": 11, "x": 12, "y": 0 },
   "targets": [
    {
     "aggregator": "sum",
     "alias": "$tag_operation",
     "downsampleAggregator": "max",
     "downsampleFillPolicy": "null",
     "downsampleInterval": "$tInterval",
     "filters": [
      {
       "filter": "$byNode",
       "groupBy": false,
       "tagk": "node",
       "type": "pm_filter"
      },
      {
       "filter": "$operation",
       "groupBy": true,
       "tagk": "operation",
       "type": "pm_filter"
      }
     ],
     "metric": "op_count"
    }
   ]
  },
  {
   "title": "Total SMB IO throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "alias": "op_inbytes",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$byNode",
       "groupBy": false,
       "tagk": "node",
       "type": "pm_filter"
      }
     ],
     "metric": "op_inbytes"
    },
    {
     "aggregator": "sum",
     "alias": "op_outbytes",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$byNode",
       "groupBy": false,
       "tagk": "node",
       "type": "pm_filter"
      }
     ],
     "metric": "op_outbytes"
    }
   ]
  }
 ]
}