{
 "title": "TCT filesystems transfers (fs + fsets)",
 "tags": [ "tct" ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "byCluster", "label": "select cluster", "query": "opentsdb" },
   {
    "name": "byFs",
    "label": "select fs",
    "query": "tag_values(tct_fs_total_persisted_bytes, gpfs_fs_name)"
   },
   {
    "name": "byNode",
    "label": "select node",
    "query": "tag_values(tct_fs_total_persisted_bytes, node)"
   },
   {
    "name": "byOperation",
    "label": "operation",
    "query": "tag_values(tct_fs_total_requests, tct_operation)"
   },
   {
    "name": "tInterval",
    "label": "t_interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": " Total number of transfer requests from filesystems per CSAP",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "alias": "$tag_tct_csap: $tag_gpfs_fs_name",
     "currentFilterKey": "node",
     "currentFilterType": "pm_filter",
     "currentFilterValue": "$byNode",
     "downsampleAggregator": "max",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "$tInterval",
     "filters": [
      {
       "filter": "",
       "groupBy": true,
       "tagk": "tct_csap",
       "type": "pm_filter"
      }
     ],
     "metric": "tct_fs_total_requests"
    },
    {
     "aggregator": "sum",
     "alias": "$tag_tct_csap: $tag_gpfs_fs_name",
     "currentFilterKey": "node",
     "currentFilterType": "pm_filter",
     "currentFilterValue": "$byNode",
     "downsampleAggregator": "max",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "$tInterval",
     "filters": [
      {
       "filter": "",
       "groupBy": true,
       "tagk": "tct_csap",
       "type": "pm_filter"
      }
     ],
     "metric": "tct_fset_total_requests"
    }
   ]
  },
  {
   "title": "Time (in second) taken for transfer requests from filesystems per CSAP",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "alias": "$tag_tct_csap: $tag_gpfs_fs_name",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "max",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "$tInterval",
     "filters": [
      {
       "filter": "",
       "groupBy": true,
       "tagk": "tct_csap",
       "type": "pm_filter"
      }
     ],
     "metric": "tct_fs_total_request_time"
    },
    {
     "aggregator": "sum",
     "alias": "$tag_tct_csap: $tag_gpfs_fs_name",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "max",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "$tInterval",
     "filters": [
      {
       "filter": "",
       "groupBy": true,
       "tagk": "tct_csap",
       "type": "pm_filter"
      }
     ],
     "metric": "tct_fset_total_request_time"
    }
   ]
  },
  {
   "title": "filesystems transfers  to a cloud provider (bytes)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "alias": "fs: $tag_gpfs_fs_name",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "max",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "$tInterval",
     "filters": [
      {
       "filter": "migrate|recall",
       "groupBy": false,
       "tagk": "tct_operation",
       "type": "pm_filter"
      },
      {
       "filter": "",
       "groupBy": true,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      }
     ],
     "metric": "tct_fs_total_persisted_bytes"
    },
    {
     "aggregator": "sum",
     "alias": "fs: $tag_gpfs_fs_name",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "max",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "$tInterval",
     "filters": [
      {
       "filter": "migrate|recall",
       "groupBy": false,
       "tagk": "tct_operation",
       "type": "pm_filter"
      },
      {
       "filter": "",
       "groupBy": true,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      }
     ],
     "metric": "tct_fset_total_persisted_bytes"
    }
   ]
  },
  {
   "title": "filesystems transfers to a cloud provider (time msec)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "alias": "fs: $tag_gpfs_fs_name",
     "downsampleAggregator": "max",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "$tInterval",
     "filters": [
      {
       "filter": "migrate|recall",
       "groupBy": false,
       "tagk": "tct_operation",
       "type": "pm_filter"
      },
      {
       "filter": "",
       "groupBy": true,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      }
     ],
     "metric": "tct_fs_total_persisted_time"
    },
    {
     "aggregator": "sum",
     "alias": "fs: $tag_gpfs_fs_name",
     "downsampleAggregator": "max",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "$tInterval",
     "filters": [
      {
       "filter": "migrate|recall",
       "groupBy": false,
       "tagk": "tct_operation",
       "type": "pm_filter"
      },
      {
       "filter": "",
       "groupBy": true,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      }
     ],
     "metric": "tct_fset_total_persisted_time"
    }
   ]
  }
 ]
}