{
 "title": "GPFS Cluster overview",
 "tags": [
  "overview",
  "health",
  "opentsdb"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "opentsdb" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregator": "sum",
     "alias": "$tag_gpfs_cluster_name",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "metric": "gpfs_pool_total_dataKB"
    }
   ]
  },
  { "gridPos": { "h": 10, "w": 15, "x": 0, "y": 2 } },
  {
   "title": "Warning events ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "-",
       "groupBy": false,
       "tagk": "gpfs_health_entity",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_health_warning_events"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "aggregator": "max",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "metric": "cpu_system"
    },
    {
     "aggregator": "max",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "metric": "cpu_user"
    }
   ]
  },
  {
   "title": "Error events ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "-",
       "groupBy": false,
       "tagk": "gpfs_health_entity",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_health_error_events"
    }
   ]
  },
  {
   "title": "Fielsystems",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "aggregator": "sum",
     "alias": "$tag_gpfs_fs_name",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "",
       "groupBy": true,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_disk_disksize"
    }
   ]
  },
  {
   "title": "Disk capacity usage by Filesystem",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 2, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($B-$A)/$B", "type": "math" }
   ]
  },
  {
   "title": "Filesystem MGR",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregator": "noop",
     "alias": "$tag_gpfs_health_entity on $tag_node",
     "downsampleAggregator": "max",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "15m",
     "filters": [
      {
       "filter": "FILESYSMGR",
       "groupBy": false,
       "tagk": "gpfs_health_component",
       "type": "pm_filter"
      },
      {
       "filter": "",
       "groupBy": true,
       "tagk": "gpfs_health_entity",
       "type": "pm_filter"
      },
      {
       "filter": "",
       "groupBy": true,
       "tagk": "node",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_health_status"
    }
   ]
  },
  {
   "title": "Filesystem READ OPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "$tag_gpfs_cluster_name",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "",
       "groupBy": true,
       "tagk": "gpfs_cluster_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_fs_read_ops"
    }
   ]
  },
  {
   "title": "Network Adapter errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A + $B", "type": "math" }
   ]
  },
  {
   "title": "Used disks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "aggregator": "sum",
     "alias": "$tag_gpfs_disk_name",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "",
       "groupBy": true,
       "tagk": "gpfs_disk_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_disk_disksize"
    }
   ]
  }
 ]
}