{
 "title": "AFM  over NFS (home/cache cluster view)",
 "tags": [
  "AFM",
  "nfs"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "homeCluster", "label": "homeCluster", "query": "opentsdb" },
   {
    "name": "byExport",
    "label": "filter by NFS export on home cluster",
    "query": "tag_values(nfs_read,export)"
   },
   {
    "name": "byPod",
    "label": "filter by regionalDR pod on home cluster",
    "query": "tag_values(nfs_read, node)"
   },
   { "name": "cacheCluster", "label": "cacheCluster", "query": "opentsdb" },
   {
    "name": "gateWayNode",
    "label": "filter by Primary Gateway node on cache cluster",
    "query": "tag_values(gpfs_afm_fset_bytes_read, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "HOME CLUSTER  $homeCluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "NFS Throughput",
   "type": "timeseries",
   "description": "Display the NFS Throughput in bytes per second.\nCompare to the mmperfmon NamedQuery 'nfsThroughput' F.e. try on the command line:\n\n# mmperfmon query nfsThroughput 3600 -b 60",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "aggregator": "noop",
     "alias": "read: $tag_export",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "filters": [
      {
       "filter": "$byExport",
       "groupBy": true,
       "tagk": "export",
       "type": "pm_filter"
      },
      {
       "filter": "$byPod",
       "groupBy": true,
       "tagk": "node",
       "type": "pm_filter"
      }
     ],
     "metric": "nfs_read"
    },
    {
     "aggregator": "noop",
     "alias": "write: $tag_export",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "filters": [
      {
       "filter": "$byExport",
       "groupBy": true,
       "tagk": "export",
       "type": "pm_filter"
      },
      {
       "filter": "$byPod",
       "groupBy": true,
       "tagk": "node",
       "type": "pm_filter"
      }
     ],
     "metric": "nfs_write"
    }
   ]
  },
  {
   "title": "NFS IO Rate",
   "type": "timeseries",
   "description": "get the NFS IOps per second",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "aggregator": "noop",
     "alias": "readOPS: $tag_export",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "filters": [
      {
       "filter": "$byExport",
       "groupBy": true,
       "tagk": "export",
       "type": "pm_filter"
      },
      {
       "filter": "$byPod",
       "groupBy": true,
       "tagk": "node",
       "type": "pm_filter"
      }
     ],
     "metric": "nfs_read_ops"
    },
    {
     "aggregator": "noop",
     "alias": "writeOPS: $tag_export",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "filters": [
      {
       "filter": "$byExport",
       "groupBy": true,
       "tagk": "export",
       "type": "pm_filter"
      },
      {
       "filter": "$byPod",
       "groupBy": true,
       "tagk": "node",
       "type": "pm_filter"
      }
     ],
     "metric": "nfs_write_ops"
    }
   ]
  },
  {
   "title": "CACHE CLUSTER $cacheCluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Used memory in bytes by the messages enqueued",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "aggregator": "noop",
     "alias": "gateWay node: $tag_node",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$gateWayNode",
       "groupBy": false,
       "tagk": "node",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_afm_used_q_memory"
    }
   ]
  },
  {
   "title": "Number of messages that are currently enqueued",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "aggregator": "noop",
     "alias": "gateWay node: $tag_node",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$gateWayNode",
       "groupBy": false,
       "tagk": "node",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_afm_used_q_memory"
    }
   ]
  },
  {
   "title": "Total number of bytes read from remote system",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "aggregator": "noop",
     "alias": "gateWay node: $tag_node",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$gateWayNode",
       "groupBy": false,
       "tagk": "node",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_afm_bytes_read"
    }
   ]
  },
  {
   "title": "Total number of bytes written to the remote system",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "aggregator": "noop",
     "alias": "gateWay node: $tag_node",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$gateWayNode",
       "groupBy": false,
       "tagk": "node",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_afm_bytes_written"
    }
   ]
  },
  {
   "title": "Total number of bytes pending, i.e. not yet written to the remote system",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "aggregator": "noop",
     "alias": "gateWay node: $tag_node",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$gateWayNode",
       "groupBy": false,
       "tagk": "node",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_afm_bytes_pending"
    }
   ]
  }
 ]
}