{
 "title": "AFM  FS view",
 "tags": [
  "afm",
  "filesystem"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "system", "label": "cacheCluster", "query": "opentsdb" },
   {
    "name": "gateWayNode",
    "label": "filter by Primary Gateway node",
    "query": "tag_values(gpfs_afm_fset_bytes_read, node)"
   },
   {
    "name": "afmFS",
    "label": "filter by AFM Filesystem",
    "query": "tag_values(gpfs_afm_fs_ops_sent, gpfs_fs_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "$afmFS (number of bytes written)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "aggregator": "noop",
     "alias": "$tag_node",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$gateWayNode",
       "groupBy": false,
       "tagk": "node",
       "type": "pm_filter"
      },
      {
       "filter": "$afmFS",
       "groupBy": false,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_afm_fs_bytes_written"
    }
   ]
  },
  {
   "title": "$afmFS (number of operations sent)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "aggregator": "noop",
     "alias": "$tag_node",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$afmFS",
       "groupBy": false,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      },
      {
       "filter": "$gateWayNode",
       "groupBy": false,
       "tagk": "node",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_afm_fs_ops_sent"
    }
   ]
  },
  {
   "title": "$afmFS (used memory in bytes by the messages queued)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "aggregator": "noop",
     "alias": "$tag_node",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$afmFS",
       "groupBy": true,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      },
      {
       "filter": "$gateWayNode",
       "groupBy": false,
       "tagk": "node",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_afm_fs_used_q_memory"
    }
   ]
  },
  {
   "title": "$afmFS (number of messages that are currently queued)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "aggregator": "noop",
     "alias": "$tag_node",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$afmFS",
       "groupBy": true,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      },
      {
       "filter": "$gateWayNode",
       "groupBy": false,
       "tagk": "node",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_afm_fs_num_queued_msgs"
    }
   ]
  },
  {
   "title": "TREND CHARTS - Total number of bytes read/written from/to the remote system for   \"$afmFS\"   filesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total number of bytes read",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "aggregator": "sum",
       "downsampleAggregator": "noop",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "$gateWayNode",
         "groupBy": false,
         "tagk": "node",
         "type": "pm_filter"
        },
        {
         "filter": "$afmFS",
         "groupBy": false,
         "tagk": "gpfs_fs_name",
         "type": "pm_filter"
        }
       ],
       "metric": "gpfs_afm_fs_bytes_read"
      }
     ]
    },
    {
     "title": "Total number of bytes written",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "aggregator": "sum",
       "downsampleAggregator": "noop",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "$gateWayNode",
         "groupBy": false,
         "tagk": "node",
         "type": "pm_filter"
        },
        {
         "filter": "$afmFS",
         "groupBy": false,
         "tagk": "gpfs_fs_name",
         "type": "pm_filter"
        }
       ],
       "metric": "gpfs_afm_fs_bytes_written"
      }
     ]
    },
    {
     "title": "Total number of bytes pending",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "aggregator": "sum",
       "downsampleAggregator": "noop",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "$gateWayNode",
         "groupBy": false,
         "tagk": "node",
         "type": "pm_filter"
        },
        {
         "filter": "$afmFS",
         "groupBy": false,
         "tagk": "gpfs_fs_name",
         "type": "pm_filter"
        }
       ],
       "metric": "gpfs_afm_fs_bytes_pending"
      }
     ]
    }
   ]
  },
  {
   "title": "TREND CHARTS - Number of operations that were sent to remote system \"$afmFS\" filesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": " Total number of operations sync",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "aggregator": "sum",
       "downsampleAggregator": "noop",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "$afmFS",
         "groupBy": false,
         "tagk": "gpfs_fs_name",
         "type": "pm_filter"
        },
        {
         "filter": "$gateWayNode",
         "groupBy": false,
         "tagk": "node",
         "type": "pm_filter"
        }
       ],
       "metric": "gpfs_afm_fs_ops_sync"
      }
     ]
    },
    {
     "title": " Total number of operations sent",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "aggregator": "sum",
       "downsampleAggregator": "noop",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "$afmFS",
         "groupBy": false,
         "tagk": "gpfs_fs_name",
         "type": "pm_filter"
        },
        {
         "filter": "$gateWayNode",
         "groupBy": false,
         "tagk": "node",
         "type": "pm_filter"
        }
       ],
       "metric": "gpfs_afm_fs_ops_sent"
      }
     ]
    },
    {
     "title": " Total number of operations expired",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "aggregator": "sum",
       "downsampleAggregator": "noop",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "$gateWayNode",
         "groupBy": false,
         "tagk": "node",
         "type": "pm_filter"
        },
        {
         "filter": "$afmFS",
         "groupBy": false,
         "tagk": "gpfs_fs_name",
         "type": "pm_filter"
        }
       ],
       "metric": "gpfs_afm_fs_ops_expired"
      }
     ]
    }
   ]
  },
  {
   "title": "TREND CHARTS - Time in seconds that a pending operation waited in the gateway queue before being sent to remote system for \"$afmFS\" filesystem.",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Average time in seconds",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "aggregator": "avg",
       "downsampleAggregator": "noop",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "$gateWayNode",
         "groupBy": false,
         "tagk": "node",
         "type": "pm_filter"
        },
        {
         "filter": "$afmFS",
         "groupBy": false,
         "tagk": "gpfs_fs_name",
         "type": "pm_filter"
        }
       ],
       "metric": "gpfs_afm_fs_avg_time"
      }
     ]
    },
    {
     "title": "Longest time in seconds",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "aggregator": "max",
       "downsampleAggregator": "noop",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "$gateWayNode",
         "groupBy": false,
         "tagk": "node",
         "type": "pm_filter"
        },
        {
         "filter": "$afmFS",
         "groupBy": false,
         "tagk": "gpfs_fs_name",
         "type": "pm_filter"
        }
       ],
       "metric": "gpfs_afm_fs_longest_time"
      }
     ]
    },
    {
     "title": "Shortest time in seconds",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "min" ] } },
     "targets": [
      {
       "aggregator": "min",
       "downsampleAggregator": "noop",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "$gateWayNode",
         "groupBy": false,
         "tagk": "node",
         "type": "pm_filter"
        },
        {
         "filter": "$afmFS",
         "groupBy": false,
         "tagk": "gpfs_fs_name",
         "type": "pm_filter"
        }
       ],
       "metric": "gpfs_afm_fs_shortest_time"
      }
     ]
    }
   ]
  },
  {
   "title": "Total number of times the connection to the remote system was established/ broken for the $afmFS filesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total number  a connection was established ",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "aggregator": "max",
       "downsampleAggregator": "noop",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "$afmFS",
         "groupBy": false,
         "tagk": "gpfs_fs_name",
         "type": "pm_filter"
        },
        {
         "filter": "$gateWayNode",
         "groupBy": false,
         "tagk": "node",
         "type": "pm_filter"
        }
       ],
       "metric": "gpfs_afm_fs_conn_esta"
      }
     ]
    },
    {
     "title": "Total number  a connection was broken",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "aggregator": "max",
       "downsampleAggregator": "noop",
       "downsampleFillPolicy": "none",
       "filters": [
        {
         "filter": "$gateWayNode",
         "groupBy": false,
         "tagk": "node",
         "type": "pm_filter"
        },
        {
         "filter": "$afmFS",
         "groupBy": false,
         "tagk": "gpfs_fs_name",
         "type": "pm_filter"
        }
       ],
       "metric": "gpfs_afm_fs_conn_broken"
      }
     ]
    }
   ]
  }
 ]
}