{
 "title": "System load overview",
 "tags": [
  "test",
  "ess",
  "opentsdb"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "opentsdb" }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": " CPU Utilization",
     "type": "piechart",
     "description": "The 3 CPU states\nThere are 3 general states your CPU can be in:\n\n    Idle, which means it has nothing to do.\n    Running a user space program, like a command shell, an email server, or a compiler.\n    Running the kernel, servicing interrupts or managing resources.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "aggregator": "max",
       "currentFilterType": "literal_or",
       "downsampleAggregator": "noop",
       "downsampleFillPolicy": "none",
       "downsampleInterval": "1",
       "filters": [
        {
         "filter": "",
         "groupBy": false,
         "tagk": "node",
         "type": "pm_filter"
        }
       ],
       "metric": "cpu_system"
      },
      {
       "aggregator": "max",
       "currentFilterType": "literal_or",
       "downsampleAggregator": "noop",
       "downsampleFillPolicy": "none",
       "downsampleInterval": "1",
       "metric": "cpu_user"
      },
      { "aggregator": "min", "downsampleAggregator": "noop", "downsampleFillPolicy": "none", "metric": "cpu_idle" }
     ]
    },
    {
     "title": " CPU contexts per Node",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "aggregator": "noop",
       "alias": "$tag_node",
       "currentFilterType": "literal_or",
       "downsampleAggregator": "noop",
       "downsampleFillPolicy": "none",
       "downsampleInterval": "1",
       "metric": "cpu_contexts"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Rate Recived Data",
     "type": "stat",
     "description": "Used metric:\nnetdev_bytes_r - Number of bytes received.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "aggregator": "rate", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "netdev_bytes_r" }
     ]
    },
    {
     "title": "Average Rate Sent Data",
     "type": "stat",
     "description": "Used metric:\nnetdev_bytes_s - Number of bytes sent",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "aggregator": "rate", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "netdev_bytes_s" }
     ]
    },
    {
     "title": "Read errors",
     "type": "stat",
     "description": "netdev_errors_r - Number of read errors.",
     "gridPos": { "h": 7, "w": 3, "x": 12, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "aggregator": "sum", "downsampleAggregator": "noop", "downsampleFillPolicy": "none", "metric": "netdev_errors_r" }
     ]
    },
    {
     "title": "Send errors",
     "type": "stat",
     "description": "netdev_errors_s - Number of write errors.",
     "gridPos": { "h": 7, "w": 3, "x": 15, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "aggregator": "sum", "downsampleAggregator": "noop", "downsampleFillPolicy": "none", "metric": "netdev_errors_s" }
     ]
    },
    {
     "title": "Read drops",
     "type": "stat",
     "description": "netdev_drops_r - Number of packets dropped while receiving",
     "gridPos": { "h": 7, "w": 3, "x": 18, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "aggregator": "sum", "downsampleAggregator": "noop", "downsampleFillPolicy": "none", "metric": "netdev_drops_r" }
     ]
    },
    {
     "title": "Send drops",
     "type": "stat",
     "description": "netdev_drops_s;Pkts;Number of packets dropped while sending",
     "gridPos": { "h": 7, "w": 3, "x": 21, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "aggregator": "sum", "downsampleAggregator": "noop", "downsampleFillPolicy": "none", "metric": "netdev_drops_s" }
     ]
    },
    {
     "title": "Aggregate Network Send/Receive data (bytesI",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "aggregator": "sum",
       "currentFilterKey": "netdev",
       "currentFilterValue": "i",
       "downsampleAggregator": "noop",
       "downsampleFillPolicy": "none",
       "metric": "netdev_bytes_r"
      },
      { "aggregator": "sum", "downsampleAggregator": "noop", "downsampleFillPolicy": "none", "metric": "netdev_bytes_s" }
     ]
    }
   ]
  },
  {
   "title": "InfiniBand Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "IB Average Rate Transmitted Data",
     "type": "stat",
     "description": "Used metric:\nport_xmit_data- Total number of data octets, which are divided by 4 (lanes), transmitted through all virtual lanes.",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 286 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "aggregator": "rate",
       "currentFilterKey": "netdev",
       "currentFilterValue": "i",
       "downsampleAggregator": "noop",
       "downsampleFillPolicy": "none",
       "metric": "port_xmit_data"
      }
     ]
    },
    {
     "title": "IB Average Rate Received Data",
     "type": "stat",
     "description": "Used metric:\nport_rcv_data\t-Total number of data octets, which are divided by 4 (lanes), received on all virtual lanes. transmitted through all virtual lanes.",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 286 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "aggregator": "rate",
       "currentFilterKey": "netdev",
       "currentFilterValue": "i",
       "downsampleAggregator": "noop",
       "downsampleFillPolicy": "none",
       "metric": "port_rcv_data"
      }
     ]
    },
    {
     "title": "IB Number of received packets containing an error",
     "type": "stat",
     "description": "port_rcv_errors -Total number of packets containing an error that were received on the port.",
     "gridPos": { "h": 6, "w": 7, "x": 10, "y": 286 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "aggregator": "sum",
       "alias": "$tag_node",
       "currentFilterType": "literal_or",
       "currentTagKey": "netdev_name",
       "downsampleAggregator": "noop",
       "downsampleFillPolicy": "none",
       "downsampleInterval": "1",
       "metric": "port_rcv_errors"
      }
     ]
    },
    {
     "title": "IB Number of outbound packets discarded",
     "type": "stat",
     "description": "port_xmit_discards - Total number of outbound packets discarded by the port because the port is down or congested.",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 286 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "aggregator": "max",
       "alias": "$tag_node",
       "currentFilterType": "literal_or",
       "currentTagKey": "netdev_name",
       "downsampleAggregator": "noop",
       "downsampleFillPolicy": "none",
       "downsampleInterval": "1",
       "metric": "port_xmit_discards"
      }
     ]
    },
    {
     "title": "IB Aggregated Received/Transmitted Data",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 292 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "aggregator": "sum",
       "currentFilterKey": "netdev",
       "currentFilterValue": "i",
       "downsampleAggregator": "sum",
       "downsampleFillPolicy": "none",
       "metric": "port_xmit_data"
      },
      { "aggregator": "sum", "downsampleAggregator": "sum", "downsampleFillPolicy": "none", "metric": "port_rcv_data" }
     ]
    }
   ]
  },
  { "title": "Filesystem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "FS Average write rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "aggregator": "rate", "downsampleAggregator": "noop", "downsampleFillPolicy": "none", "metric": "gpfs_fs_bytes_written" }
   ]
  },
  {
   "title": "FS writes aggregated per node",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "aggregator": "sum",
     "alias": "$tag_node",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1",
     "filters": [
      {
       "filter": "",
       "groupBy": true,
       "tagk": "node",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_fs_bytes_written"
    }
   ]
  },
  {
   "title": "The longest time spent waiting for a disk write operation per filesystem",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "aggregator": "max",
     "alias": " $tag_gpfs_fs_name",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1",
     "filters": [
      {
       "filter": "",
       "groupBy": true,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_fs_max_disk_wait_wr"
    }
   ]
  },
  {
   "title": "FS Average read rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "aggregator": "rate", "downsampleAggregator": "noop", "downsampleFillPolicy": "none", "metric": "gpfs_fs_bytes_read" }
   ]
  },
  {
   "title": "FS reads aggregated per node",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "aggregator": "sum",
     "alias": "$tag_node",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1",
     "filters": [
      {
       "filter": "",
       "groupBy": true,
       "tagk": "node",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_fs_bytes_read"
    }
   ]
  },
  {
   "title": "The longest time spent waiting for a disk read operation per filesystem",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "aggregator": "max",
     "alias": " $tag_gpfs_fs_name",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1",
     "filters": [
      {
       "filter": "",
       "groupBy": true,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_fs_max_disk_wait_rd"
    }
   ]
  },
  {
   "title": "Filesystem (Application view)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "FIS number of open calls (max)",
     "type": "stat",
     "description": "Used metric:\ngpfs_fis_open_calls - Number of open calls.",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 493 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "aggregator": "max", "downsampleAggregator": "noop", "downsampleFillPolicy": "none", "metric": "gpfs_fis_open_calls" }
     ]
    },
    {
     "title": "FIS number of close calls (max)",
     "type": "stat",
     "description": "Used metric:\ngpfs_fis_close_calls - Number of close calls",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 493 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "aggregator": "max", "downsampleAggregator": "noop", "downsampleFillPolicy": "none", "metric": "gpfs_fis_close_calls" }
     ]
    },
    {
     "title": "FIS number of read calls (max)",
     "type": "stat",
     "description": "Used metric:\ngpfs_fis_read_calls - Number of read calls",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 493 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "aggregator": "max", "downsampleAggregator": "noop", "downsampleFillPolicy": "none", "metric": "gpfs_fis_read_calls" }
     ]
    },
    {
     "title": "FIS number of write calls (max)",
     "type": "stat",
     "description": "Used metric:\ngpfs_fis_write_calls: Number of write calls",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 493 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "aggregator": "max", "downsampleAggregator": "noop", "downsampleFillPolicy": "none", "metric": "gpfs_fis_write_calls" }
     ]
    },
    {
     "title": "FIS number of inode updates (max)",
     "type": "stat",
     "description": "Used metric:\ngpfs_fis_inodes_written - Number of inode updates to disk",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 493 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "aggregator": "max", "downsampleAggregator": "noop", "downsampleFillPolicy": "none", "metric": "gpfs_fis_inodes_written" }
     ]
    },
    {
     "title": "FIS number of readdir calls (max)",
     "type": "stat",
     "description": "Used metric:\ngpfs_fis_readdir_calls - Number of readdir calls",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 493 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "aggregator": "max", "downsampleAggregator": "noop", "downsampleFillPolicy": "none", "metric": "gpfs_fis_readdir_calls" }
     ]
    },
    {
     "title": "Aggregated FIS bytes Read/Write",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 500 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "aggregator": "sum",
       "downsampleAggregator": "noop",
       "downsampleFillPolicy": "none",
       "downsampleInterval": "1",
       "metric": "gpfs_fis_bytes_read"
      },
      {
       "aggregator": "sum",
       "downsampleAggregator": "sum",
       "downsampleFillPolicy": "none",
       "downsampleInterval": "1",
       "metric": "gpfs_fis_bytes_written"
      }
     ]
    },
    {
     "title": "FIS read rate per filesystem/node",
     "type": "table",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 500 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "aggregator": "rate",
       "alias": " $tag_gpfs_fs_name: $tag_node",
       "currentFilterType": "literal_or",
       "downsampleAggregator": "noop",
       "downsampleFillPolicy": "none",
       "downsampleInterval": "1",
       "filters": [
        {
         "filter": "",
         "groupBy": true,
         "tagk": "gpfs_fs_name",
         "type": "pm_filter"
        }
       ],
       "metric": "gpfs_fis_bytes_read"
      }
     ]
    },
    {
     "title": "FIS write rate per filesystem/node",
     "type": "table",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 500 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "aggregator": "rate",
       "alias": " $tag_gpfs_fs_name: $tag_node",
       "currentFilterType": "literal_or",
       "downsampleAggregator": "noop",
       "downsampleFillPolicy": "none",
       "downsampleInterval": "1",
       "filters": [
        {
         "filter": "",
         "groupBy": true,
         "tagk": "gpfs_fs_name",
         "type": "pm_filter"
        }
       ],
       "metric": "gpfs_fis_bytes_written"
      }
     ]
    }
   ]
  }
 ]
}