{
 "title": "ESS Hardware Performance overview",
 "tags": [
  "hardware",
  "ess",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "Node",
    "query": {
     "query": "label_values(gpfs_hw_speed,node)"
    }
   },
   {
    "name": "psu",
    "label": "PSU",
    "query": {
     "query": "label_values(gpfs_hw_current,gpfs_hw_entity)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HW Highest Temperature ",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gpfs_hw_temp{node=~\"$Node\"}) by(node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AVG fan speed",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gpfs_hw_speed{node=~\"$Node\"}) by(node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power consumption total",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "gpfs_hw_current{node=~\"$Node\", gpfs_hw_entity=~\"psu.*_in\"} * gpfs_hw_voltage{node=~\"$Node\", gpfs_hw_entity=~\"psu.*_in\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}