{
 "title": "NSD Server",
 "tags": [
  "default",
  "node"
 ],
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   { "name": "byCluster", "label": "select cluster", "query": "opentsdb" },
   { "name": "gpfsMetrics_nsd_server", "label": "metric1", "query": "metrics(gpfs_nsdds_)" },
   { "name": "gpfsMetrics_netdev1", "label": "throughput", "query": "metrics(netdev_b)" },
   { "name": "gpfsMetrics_netdev2", "query": "metrics(netdev_e.*)" },
   {
    "name": "byDisk",
    "query": "tag_values($gpfsMetrics_nsd_server,gpfs_disk_name)"
   },
   {
    "name": "byNode",
    "query": "tag_values($gpfsMetrics_nsd_server, node)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard displays all nodes that are NSD servers with specific performance information related to NSDs. If there are no NSD servers in the cluster, this graphs will show nothing.\n"
   },
   "content": "This dashboard displays all nodes that are NSD servers with specific performance information related to NSDs. If there are no NSD servers in the cluster, this graphs will show nothing.\n"
  },
  {
   "title": "Overall Data Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "filters": [
      {
       "filter": "",
       "groupBy": true,
       "tagk": "node",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_nsdds_bytes_read"
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "filters": [
      {
       "filter": "",
       "groupBy": true,
       "tagk": "node",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_nsdds_bytes_written"
    }
   ]
  },
  {
   "title": "Overall Server workload (OPs)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "filters": [
      {
       "filter": "",
       "groupBy": true,
       "tagk": "node",
       "type": "literal_or"
      }
     ],
     "metric": "gpfs_nsdds_read_ops"
    },
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "filters": [
      {
       "filter": "",
       "groupBy": true,
       "tagk": "node",
       "type": "literal_or"
      }
     ],
     "metric": "gpfs_nsdds_write_ops"
    }
   ]
  },
  {
   "title": "\"$gpfsMetrics_nsd_server\" by Node: \"$byNode\"",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "\"disk: [[tag_gpfs_disk_name]]\"",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$byNode",
       "groupBy": true,
       "tagk": "node",
       "type": "pm_filter"
      },
      {
       "filter": "",
       "groupBy": true,
       "tagk": "gpfs_disk_name",
       "type": "pm_filter"
      }
     ],
     "metric": "$gpfsMetrics_nsd_server"
    }
   ]
  },
  {
   "title": "\"$gpfsMetrics_nsd_server\" by disk: \"$byDisk\"",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "alias": "\"disk: [[tag_gpfs_disk_name]]\"",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$byDisk",
       "groupBy": true,
       "tagk": "gpfs_disk_name",
       "type": "pm_filter"
      }
     ],
     "metric": "$gpfsMetrics_nsd_server"
    }
   ]
  }
 ]
}