{
 "title": "ESS Hardware Performance overview",
 "tags": [
  "hardware",
  "ess",
  "opentsdb"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "opentsdb" },
   {
    "name": "Node",
    "query": "tag_values(gpfs_hw_speed, node)"
   },
   {
    "name": "psu",
    "label": "PSU",
    "query": "tag_values(gpfs_hw_current, gpfs_hw_entity)"
   }
  ]
 },
 "panels": [
  {
   "title": "HW Highest Temperature ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregator": "max",
     "alias": "$tag_node",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$Node",
       "groupBy": true,
       "tagk": "node",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_hw_temp"
    }
   ]
  },
  {
   "title": "AVG fan speed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "alias": "$tag_node",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$Node",
       "groupBy": true,
       "tagk": "node",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_hw_speed"
    }
   ]
  },
  {
   "title": "Power consumption total",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expression": "$A*$B", "type": "math" }
   ]
  }
 ]
}