{
 "title": "Filesets Capacity Utilization",
 "tags": [
  "capacity",
  "advanced"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "mFileset", "label": "GPFSfileset metrics", "query": "metrics(gpfs_fset_)" },
   {
    "name": "byFsName",
    "query": "tag_values($mFileset, gpfs_fs_name)"
   },
   { "name": "filterBy", "label": "filterBy", "query": "tag_names($gpfsMetrics)" },
   {
    "name": "values",
    "label": "values",
    "query": "tag_values($gpfsMetrics, $filterBy)"
   },
   { "name": "gpfsMetrics", "label": "metric1", "query": "metrics(gpfs_)" },
   {
    "name": "byPoolName",
    "query": "tag_values($gpfsMetrics, gpfs_diskpool_name)"
   },
   {
    "name": "byFileset",
    "query": "tag_values($mFileset,gpfs_fset_name, gpfs_fs_name=$byFsName)"
   }
  ]
 },
 "panels": [
  {
   "title": "Notice about Filesets !",
   "type": "text",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "You can create, edit, or delete filesets. Filesets allows to partition a file system for administrative operations at a finer granularity than the entire file system.\nYou can create the following two types of filesets:\n\n    Independent filesets\n    Dependent filesets\n\nAn independent fileset has a separate inode space, but shares physical storage with the remainder of the file system. Maximum number and preallocation of inodes for an independent fileset can be specified while creating fileset.\n\nA dependent fileset shares the inode space and snapshot capability of the containing independent fileset. Inodes allocation for independent fileset is independent of the inode quota limit set for the containing file system. That is, an independent fileset has its own separate quota limits. User and group quotas can be created for any independent or dependent fileset if they are enabled for the containing file system.  Dependent filesets can also reside directly within the root file system, which is sometimes called the global fileset. When an independent fileset is deleted, any dependent filesets  are also deleted. If a dependent fileset is defined within an independent fileset, it can be linked only inside of its own inode space.\n\nWhen quotas are managed at the fileset level, those quotas have a higher priority than those set at the file system level.\n\n"
   },
   "content": "You can create, edit, or delete filesets. Filesets allows to partition a file system for administrative operations at a finer granularity than the entire file system.\nYou can create the following two types of filesets:\n\n    Independent filesets\n    Dependent filesets\n\nAn independent fileset has a separate inode space, but shares physical storage with the remainder of the file system. Maximum number and preallocation of inodes for an independent fileset can be specified while creating fileset.\n\nA dependent fileset shares the inode space and snapshot capability of the containing independent fileset. Inodes allocation for independent fileset is independent of the inode quota limit set for the containing file system. That is, an independent fileset has its own separate quota limits. User and group quotas can be created for any independent or dependent fileset if they are enabled for the containing file system.  Dependent filesets can also reside directly within the root file system, which is sometimes called the global fileset. When an independent fileset is deleted, any dependent filesets  are also deleted. If a dependent fileset is defined within an independent fileset, it can be linked only inside of its own inode space.\n\nWhen quotas are managed at the fileset level, those quotas have a higher priority than those set at the file system level.\n\n"
  },
  {
   "title": "\"$mFileset\" per fileset in \"$byFsName\"",
   "type": "graph",
   "gridPos": { "h": 10, "w": 14, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "noop",
     "alias": "$tag_gpfs_fset_name",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "5m",
     "filters": [
      {
       "filter": "",
       "groupBy": true,
       "tagk": "gpfs_fset_name",
       "type": "pm_filter"
      },
      {
       "filter": "$byFsName",
       "groupBy": false,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      }
     ],
     "metric": "$mFileset"
    }
   ]
  },
  {
   "title": "Filesets capacity utilization aggregated in \"$byFsName\"",
   "type": "graph",
   "description": "On this graph you can monitor filesystem inodes allocation and usage",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "currentFilterKey": "gpfs_fs_name",
     "currentFilterType": "pm_filter",
     "currentFilterValue": "$byFsName",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "5m",
     "metric": "gpfs_fset_allocInodes"
    },
    {
     "aggregator": "sum",
     "currentFilterKey": "gpfs_fs_name",
     "currentFilterType": "pm_filter",
     "currentFilterValue": "$byFsName",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "5m",
     "metric": "gpfs_fset_freeInodes"
    },
    {
     "aggregator": "sum",
     "currentFilterKey": "gpfs_fs_name",
     "currentFilterType": "pm_filter",
     "currentFilterValue": "$byFsName",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "5m",
     "metric": "gpfs_fset_maxInodes"
    },
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none" }
   ]
  },
  {
   "title": "\"$byFileset\" capacity utilization",
   "type": "graph",
   "description": "On this graph you can monitor  inodes allocation and usage for selected fileset",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "noop",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "5m",
     "filters": [
      {
       "filter": "$byFsName",
       "groupBy": false,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      },
      {
       "filter": "$byFileset",
       "groupBy": true,
       "tagk": "gpfs_fset_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_fset_allocInodes"
    },
    {
     "aggregator": "noop",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "5m",
     "filters": [
      {
       "filter": "$byFileset",
       "groupBy": true,
       "tagk": "gpfs_fset_name",
       "type": "pm_filter"
      },
      {
       "filter": "$byFsName",
       "groupBy": false,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_fset_freeInodes"
    },
    {
     "aggregator": "noop",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "5m",
     "filters": [
      {
       "filter": "$byFileset",
       "groupBy": true,
       "tagk": "gpfs_fset_name",
       "type": "pm_filter"
      },
      {
       "filter": "$byFsName",
       "groupBy": false,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_fset_maxInodes"
    }
   ]
  },
  {
   "title": "Block quotas for \"$byFileset\"",
   "type": "graph",
   "description": "This chart contains metrics values telling you about :\n \tUsed capacity in a fileset, as reported by the quota mechanism. Soft and hard quota limit for capacity in a fileset.",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "currentFilterKey": "gpfs_fset_name",
     "currentFilterType": "pm_filter",
     "currentFilterValue": "$byFileset",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "12h",
     "metric": "gpfs_rq_blk_hard_limit"
    },
    {
     "aggregator": "sum",
     "currentFilterKey": "gpfs_fset_name",
     "currentFilterType": "pm_filter",
     "currentFilterValue": "$byFileset",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "12h",
     "metric": "gpfs_rq_blk_soft_limit"
    },
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "12h",
     "filters": [
      {
       "filter": "$byFileset",
       "groupBy": true,
       "tagk": "gpfs_fset_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_rq_blk_current"
    },
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "12h",
     "filters": [
      {
       "filter": "$byFileset",
       "groupBy": true,
       "tagk": "gpfs_fset_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_rq_blk_in_doubt"
    }
   ]
  },
  {
   "title": "File quotas for \"$byFileset\"",
   "type": "graph",
   "description": "This chart shows you 'used inodes in a fileset', as reported by the quota mechanism. Soft and hard inodes limits set for this fileset.",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "filters": [
      {
       "filter": "$byFileset",
       "groupBy": true,
       "tagk": "gpfs_fset_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_rq_file_hard_limit"
    },
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$byFileset",
       "groupBy": true,
       "tagk": "gpfs_fset_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_rq_file_soft_limit"
    },
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$byFileset",
       "groupBy": true,
       "tagk": "gpfs_fset_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_rq_file_current"
    },
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$byFileset",
       "groupBy": true,
       "tagk": "gpfs_fset_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_rq_file_in_doubt"
    }
   ]
  }
 ]
}