{
 "title": "IBM Storage Scale Network Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Data source", "query": "opentsdb" }
  ]
 },
 "panels": [
  {
   "title": "IBM Storage Scale",
   "type": "text",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 0 },
   "options": {
    "content": "# Network Overview\n\nMonitor cluster network by looking at interface statistics (netdev_*) and Scale daemon socket statistics (gpfs_tscom_*).\nRDMA traffic is not considered on this dashboard.\n\nTypical network issues\n* TCP Packet loss \n  * Increased loss & retransmit counts\n  * Usually higher RTT \n  * CA state 3 (moderate loss) or 4 (significant loss)\n* Packet corruption\n  * Network drops on interface level\n  * Network errors on interface level\n* Slow network / delays\n  * High RTT / RTTVar\n* Network interruptions \n  * Increased number of reconnects \n  * Number of established connections goes down"
   }
  },
  { "title": "Network Interface Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Network Throughput receive/send",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "netdev_bytes_r" },
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "netdev_bytes_s" }
   ]
  },
  {
   "title": "Dropped Packets on all interfaces",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "aggregator": "sum", "downsampleAggregator": "noop", "downsampleFillPolicy": "none", "metric": "netdev_drops_r" },
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "netdev_drops_s" }
   ]
  },
  {
   "title": "Packet Errors on all interfaces",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "aggregator": "sum", "downsampleAggregator": "noop", "downsampleFillPolicy": "none", "metric": "netdev_errors_r" },
    { "aggregator": "sum", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "netdev_errors_s" }
   ]
  },
  { "title": "Scale Daemon Socket statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Reconnects",
   "type": "bargauge",
   "description": "New or reconnected socket connection between two nodes. Sockets can be established and closed on demand, depending on the role of the node",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "aggregator": "sum", "downsampleAggregator": "noop", "downsampleFillPolicy": "none", "metric": "gpfs_tscom_reconnect" }
   ]
  },
  {
   "title": "Lost packets",
   "type": "bargauge",
   "description": "Lost packets (snapshot of lost packets in flight) ",
   "gridPos": { "h": 10, "w": 3, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "aggregator": "sum", "downsampleAggregator": "noop", "downsampleFillPolicy": "none", "metric": "gpfs_tscom_lost" }
   ]
  },
  {
   "title": "Packet retrans",
   "type": "bargauge",
   "description": "Current retrans packets in flight",
   "gridPos": { "h": 10, "w": 3, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "aggregator": "sum", "downsampleAggregator": "noop", "downsampleFillPolicy": "none", "metric": "gpfs_tscom_retrans" }
   ]
  },
  {
   "title": "Retransmits",
   "type": "bargauge",
   "description": "The number of timeouts (RTO based re-transmissions) within a sequence. ",
   "gridPos": { "h": 10, "w": 3, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "aggregator": "sum", "downsampleAggregator": "noop", "downsampleFillPolicy": "none", "metric": "gpfs_tscom_retransmits" }
   ]
  },
  {
   "title": "Overall Number of established Socket Connections (Cluster Wide)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 11, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "aggregator": "noop",
     "downsampleAggregator": "max",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "20s",
     "filters": [
      {
       "filter": "",
       "groupBy": true,
       "tagk": "node",
       "type": "iliteral_or"
      },
      {
       "filter": "",
       "groupBy": true,
       "tagk": "gpfs_tscom_destination",
       "type": "literal_or"
      },
      {
       "filter": "",
       "groupBy": true,
       "tagk": "gpfs_tscom_connection",
       "type": "literal_or"
      }
     ],
     "metric": "gpfs_tscom_stat"
    }
   ]
  },
  {
   "title": "Sockets with bad \"Congestion State\"",
   "type": "bargauge",
   "description": "Count the number of occurences when a socket ca_state is not OPEN (0) ",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "aggregator": "max",
     "downsampleAggregator": "max",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "60m",
     "filters": [
      {
       "filter": "",
       "groupBy": true,
       "tagk": "gpfs_tscom_destination",
       "type": "pm_filter"
      },
      {
       "filter": "",
       "groupBy": true,
       "tagk": "node",
       "type": "iliteral_or"
      }
     ],
     "metric": "gpfs_tscom_ca_stat"
    }
   ]
  },
  {
   "title": "Congestion State by target host",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 11, "x": 12, "y": 27 },
   "targets": [
    {
     "aggregator": "max",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "30m",
     "filters": [
      {
       "filter": "",
       "groupBy": true,
       "tagk": "gpfs_tscom_destination",
       "type": "literal_or"
      }
     ],
     "metric": "gpfs_tscom_ca_stat"
    }
   ]
  },
  { "title": "Time Series", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Round Trip Time (RTT) by target host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "",
       "groupBy": true,
       "tagk": "gpfs_tscom_destination",
       "type": "iliteral_or"
      }
     ],
     "metric": "gpfs_tscom_rtt"
    }
   ]
  },
  {
   "title": "Round Trip Time (RTT) by \"Source Host\"",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "",
       "groupBy": true,
       "tagk": "node",
       "type": "iliteral_or"
      }
     ],
     "metric": "gpfs_tscom_rtt"
    }
   ]
  },
  {
   "title": "Retransmission timeout (RTO )",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "aggregator": "max",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "null",
     "filters": [
      {
       "filter": "",
       "groupBy": true,
       "tagk": "gpfs_tscom_destination",
       "type": "literal_or"
      }
     ],
     "metric": "gpfs_tscom_rto"
    }
   ]
  },
  {
   "title": "Round Trip Time Variance (RTTVAR)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "aggregator": "max",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "null",
     "filters": [
      {
       "filter": "",
       "groupBy": true,
       "tagk": "gpfs_tscom_destination",
       "type": "literal_or"
      }
     ],
     "metric": "gpfs_tscom_rttvar"
    }
   ]
  },
  {
   "title": "Reconnects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 54 },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "null",
     "filters": [
      {
       "filter": "",
       "groupBy": true,
       "tagk": "gpfs_tscom_destination",
       "type": "literal_or"
      },
      {
       "filter": "",
       "groupBy": true,
       "tagk": "node",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_tscom_reconnect"
    }
   ]
  },
  {
   "title": "Network Lost Pakets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 54 },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "",
       "groupBy": true,
       "tagk": "gpfs_tscom_destination",
       "type": "iliteral_or"
      }
     ],
     "metric": "gpfs_tscom_lost"
    }
   ]
  }
 ]
}