{
 "title": "Fileset Quota Limits",
 "description": "This dashboard could be used to monitor file system usage and quota information per file set.\n",
 "tags": [
  "capacity",
  "fileset",
  "quota"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "System", "query": "opentsdb" },
   {
    "name": "byFilesystem",
    "query": "tag_values(gpfs_rq_blk_current, gpfs_fs_name)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "**Additional info:**           If the panels on the left side do not show any data, please quickly scroll down and up the entire dashboard.\r\n                               After reading this message, you can remove this text panel from the dashboard entirely."
   }
  },
  {
   "title": "Top 5 filesets approaching the soft block quotas",
   "type": "table",
   "description": "This graph is based on the metrics provided by the GPFSFilesetQuota sensor. The table shows the top 5 $byFilesystem filesets with the highest kilobyte usage based on the assigned soft quota limit.\n\n**Note that the GPFSFilesetQuota sensor runs once per hour. \n\nThe percentage is calculated as follows\nmax(gpfs_rq_blk_current /gpfs_rq_blk_soft_limit) from gpfs_fs_name=$byFilesystem.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "panelId": 3 }
   ]
  },
  {
   "title": "The amount of disk space (kilobytes) currently in use",
   "type": "timeseries",
   "description": "This Graph based on GPFSFilesetQuota sensor metric gpfs_rq_blk_current.\n",
   "gridPos": { "h": 8, "w": 13, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$byFilesystem",
       "groupBy": false,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_rq_blk_current"
    }
   ]
  },
  {
   "title": "$byFilesystem disk capacity usage",
   "type": "gauge",
   "description": "This Graph based on the metrics of the GPFSDiskCap sensor.\n\n**Note**  that the GPFSDiskCap sensor is running once per day. \n In the first 24h after the filesystem creation there will be probably no value shown. \n\nThe percentage value is calculated as follows:\nsum(gpfs_disk_disksize) - (sum(gpfs_disk_free_fullkb) ) /sum(gpfs_disk_disksize) from gpfs_fs_name=$byFilesystem\n\nClick on the value in the graph to switch to the detail view.",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($B-$A)/$B", "type": "math" }
   ]
  },
  {
   "title": "Top 5 filesets approaching the soft file quotas",
   "type": "table",
   "description": "This graph is based on the metrics provided by the GPFSFilesetQuota sensor. The table shows the top 5 $byFilesystem filesets with the highest inodes(files) usage based on the assigned soft quota limit.\n\n**Note that the GPFSFilesetQuota sensor runs once per hour. \n\nThe percentage is calculated as follows\nmax(gpfs_rq_file_current /gpfs_rq_file_soft_limit) from gpfs_fs_name=$byFilesystem.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "panelId": 14 }
   ]
  },
  {
   "title": "Sum of files (inodes) currently in use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$byFilesystem",
       "groupBy": false,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_rq_file_current"
    }
   ]
  },
  {
   "title": "$byFilesystem inode capacity usage",
   "type": "gauge",
   "description": "This Graph based on the metrics of the GPFSInodeCap sensor.\n\n**Note** that the GPFSInodeCap is not an independent sensor in the perfmon config, \nbut a sub-sensor of the GPFSDiskCap sensor which is running once per day. \nIn the first 24h after the filesystem creation there will be probably no value shown. \n\nThe percentage value is calculated as follows:\ngpfs_fs_inode_used /gpfs_fs_inode_max from gpfs_fs_name=$byFilesystem\n\nClick on the value in the graph to switch to the detail view.",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  { "gridPos": { "h": 15, "w": 12, "x": 0, "y": 18 } },
  { "gridPos": { "h": 15, "w": 12, "x": 12, "y": 18 } }
 ]
}