{
 "title": "Filesystem inodes overview",
 "description": "This dashboard can be used to monitor the inode usage of independent file sets in the selected filesystem.",
 "tags": [
  "fileset",
  "filesystem",
  "inode"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "byCluster", "label": "select cluster", "query": "opentsdb" },
   {
    "name": "byFilesystem",
    "query": "tag_values(gpfs_disk_free_fullkb, gpfs_fs_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "$byFilesystem max number of inodes",
   "type": "stat",
   "description": "The total inodes value in $byFilesystem is calculated as follows:\ngpfs_fs_inode_max from gpfs_fs_name=$byFilesystem",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregator": "noop",
     "alias": "$tag_gpfs_fs_name",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$byFilesystem",
       "groupBy": true,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_fs_inode_max"
    }
   ]
  },
  {
   "title": "$byFilesystem allocated inodes per fileset",
   "type": "bargauge",
   "description": "This Graph based on the metrics of the GPFSFileset sensor.\n\n**Note**  that the GPFSDiskCap sensor is running every 5 min. \n\n\nThe allocated inodes per independent fileset in $byFilesystem is calculated as follows:\ngpfs_fset_allocInodes  from gpfs_fs_name=$byFilesystem",
   "gridPos": { "h": 13, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregator": "noop",
     "alias": "$tag_gpfs_fset_name",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$byFilesystem",
       "groupBy": false,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_fset_allocInodes"
    }
   ]
  },
  {
   "title": "$byFilesystem free inode utilization",
   "type": "gauge",
   "description": "This Graph based on the metrics of the GPFSInodeCap sensor.\n\n**Note** that the GPFSInodeCap is not an independent sensor in the perfmon config, but a sub-sensor of the GPFSDiskCap sensor.\nThe GPFSDiskCap sensor is running once per day. \n In the first 24h after the filesystem creation there will be probably no value shown. \n\nThe percentage value is calculated as follows:\nsum(gpfs_fs_inode_free) /sum(gpfs_fs_inode_max) from gpfs_fs_name=$byFilesystem",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  }
 ]
}