{
 "title": "File Systems View",
 "tags": [
  "default",
  "node"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "byCluster", "label": "select cluster", "query": "opentsdb" },
   { "name": "gpfsMetrics_fs1", "label": "metric1", "query": "metrics(gpfs_fs_bytes*)" },
   { "name": "gpfsMetrics_fs2", "label": "metric2", "query": "metrics(gpfs_fs_.*_ops)" },
   {
    "name": "byFsName",
    "query": "tag_values($gpfsMetrics_fs1, gpfs_fs_name)"
   },
   {
    "name": "byNode",
    "query": "tag_values( $gpfsMetrics_fs1, node)"
   },
   { "name": "filterBy", "label": "filterBy", "query": "tag_names($gpfsMetrics)" },
   {
    "name": "values",
    "label": "values",
    "query": "tag_values($gpfsMetrics, $filterBy)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This View provides performance details of all File Systems mounted on the node. You can view the file systems read or write throughput,  number of read/ write operations. \nYou can switch the graph metric display  through the metric1, metric2 selection. Also you can limit the view perspective to a  particular filesystem (use *'byFsName'* drop down list)\nor a mounted node (use *'byNode'* drop down list).\n"
   }
  },
  {
   "title": "OVERVIEW(gpfs_fs_bytes_read & gpfs_fs_bytes_written)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "filters": [
      {
       "groupBy": true,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_fs_bytes_read"
    },
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "filters": [
      {
       "groupBy": true,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_fs_bytes_written"
    }
   ]
  },
  {
   "title": "OVERVIEW( gpfs_fs_read_ops & gpfs_fs_write_ops)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "filters": [
      {
       "groupBy": true,
       "tagk": "node",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_fs_read_ops"
    },
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "filters": [
      {
       "groupBy": true,
       "tagk": "node",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_fs_write_ops"
    }
   ]
  },
  {
   "title": "\"$gpfsMetrics_fs1\" by File System name: \"$byFsName\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "aggregator": "noop",
     "alias": "$tag_node",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$byFsName",
       "groupBy": true,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      }
     ],
     "metric": "$gpfsMetrics_fs1"
    }
   ]
  },
  {
   "title": "\"$gpfsMetrics_fs1\" by Node: \"$byNode\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "aggregator": "noop",
     "alias": "$tag_gpfs_fs_name",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$byNode",
       "groupBy": true,
       "tagk": "node",
       "type": "iliteral_or"
      }
     ],
     "metric": "$gpfsMetrics_fs1"
    }
   ]
  },
  {
   "title": "\"$gpfsMetrics_fs2\" by File System name: \"$byFsName\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "aggregator": "noop",
     "alias": "$tag_node",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$byFsName",
       "groupBy": true,
       "tagk": "gpfs_fs_name",
       "type": "iliteral_or"
      }
     ],
     "metric": "$gpfsMetrics_fs2"
    }
   ]
  },
  {
   "title": "\"$gpfsMetrics_fs2\" by Node: \"$byNode\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "aggregator": "noop",
     "alias": "$tag_gpfs_fs_name",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$byNode",
       "groupBy": true,
       "tagk": "node",
       "type": "iliteral_or"
      }
     ],
     "metric": "$gpfsMetrics_fs2"
    }
   ]
  }
 ]
}