{
 "title": "Network",
 "tags": [
  "default",
  "node"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "byCluster", "label": "select cluster", "query": "opentsdb" },
   { "name": "gpfsMetrics_netdev_all", "label": "metric1", "query": "metrics(netdev_bytes_.*)" },
   { "name": "gpfsMetrics_netdev_all2", "label": "metric2", "query": "metrics(netdev_errors_.*)" },
   { "name": "gpfsMetrics_netdev1", "label": "throughput", "query": "metrics(netdev_b)" },
   { "name": "gpfsMetrics_netdev2", "query": "metrics(netdev_e)" },
   {
    "name": "byNetDev",
    "query": "tag_values($gpfsMetrics_netdev_all, netdev_name)"
   },
   {
    "name": "byNode",
    "query": "tag_values($gpfsMetrics_netdev_all, node)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard displays the NETWORK  performance details.\nFor example, the *'NETWORK throughput'* graph shows you number of bytes of data sent and received by the network interface, or  the *'NETWORK errors'* graph provides you the number of receive and \nsend errors detected by the network interface. Additionally you can observe Bytes Read/Received  on the network per node or per adapter by selecting metric1, metric2, byNetDev(adapter name) and byNode(node name)\n"
   }
  },
  {
   "title": "NETWORK throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "sum",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "10m",
     "metric": "netdev_bytes_r"
    },
    {
     "aggregator": "sum",
     "downsampleAggregator": "sum",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "10m",
     "metric": "netdev_bytes_s"
    }
   ]
  },
  {
   "title": "NETWORK Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "metric": "netdev_errors_r"
    },
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "metric": "netdev_errors_s"
    }
   ]
  },
  {
   "title": "\"$gpfsMetrics_netdev_all\" by Node: \"$byNode\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "aggregator": "noop",
     "alias": "$tag_netdev_name",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "5m",
     "filters": [
      {
       "filter": "$byNode",
       "groupBy": true,
       "tagk": "node",
       "type": "pm_filter"
      }
     ],
     "metric": "$gpfsMetrics_netdev_all"
    }
   ]
  },
  {
   "title": "\"$gpfsMetrics_netdev_all\" by adapter: \"$byNetDev\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "aggregator": "noop",
     "alias": "$tag_node",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "5m",
     "filters": [
      {
       "filter": "$byNetDev",
       "groupBy": true,
       "tagk": "netdev_name",
       "type": "pm_filter"
      }
     ],
     "metric": "$gpfsMetrics_netdev_all"
    }
   ]
  },
  {
   "title": "\"$gpfsMetrics_netdev_all2\" by Node: \"$byNode\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "aggregator": "noop",
     "alias": "$tag_netdev_name",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$byNode",
       "groupBy": true,
       "tagk": "node",
       "type": "pm_filter"
      }
     ],
     "metric": "$gpfsMetrics_netdev_all2"
    }
   ]
  },
  {
   "title": "\"$gpfsMetrics_netdev_all2\" by adapter: \"$byNetDev\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "aggregator": "noop",
     "alias": "$tag_node",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "5m",
     "filters": [
      {
       "filter": "$byNetDev",
       "groupBy": true,
       "tagk": "netdev_name",
       "type": "pm_filter"
      }
     ],
     "metric": "$gpfsMetrics_netdev_all2"
    }
   ]
  }
 ]
}