{
 "title": "Fileset Quotas",
 "tags": [
  "default",
  "capacity"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "byCluster", "label": "select cluster", "query": "opentsdb" },
   { "name": "gpfsMetrics", "label": "metric1", "query": "metrics(gpfs_fs.*)" },
   { "name": "gpfsMetrics_quota1", "label": "select quota metric", "query": "metrics(gpfs_rq_)" },
   {
    "name": "byFsName",
    "label": "select filesystem",
    "query": "tag_values($gpfsMetrics, gpfs_fs_name)"
   },
   {
    "name": "byFileset",
    "label": "select fileset",
    "query": "tag_values($gpfsMetrics_quota1, gpfs_fset_name)"
   },
   { "name": "gpfsMetrics_quota", "label": "select quota metric", "query": "metrics(gpfs_rq_)" },
   { "name": "filterBy", "label": "filterBy", "query": "tag_names($gpfsMetrics)" },
   {
    "name": "values",
    "label": "values",
    "query": "tag_values($gpfsMetrics, $filterBy)"
   },
   {
    "name": "byPoolName",
    "query": "tag_values($gpfsMetrics, gpfs_diskpool_name)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 0 },
   "options": {
    "content": "The quota report lists:\n\n    Number of files used\n    Amount of disk space used\n    Current quota limits\n    In doubt quotas (disk space allocated but currently unaccounted for)\n\n"
   },
   "content": "The quota report lists:\n\n    Number of files used\n    Amount of disk space used\n    Current quota limits\n    In doubt quotas (disk space allocated but currently unaccounted for)\n\n"
  },
  {
   "title": "FILESETS \"$gpfsMetrics_quota\"",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "",
       "groupBy": true,
       "tagk": "gpfs_fset_name",
       "type": "pm_filter"
      }
     ],
     "metric": "$gpfsMetrics_quota"
    }
   ]
  },
  {
   "title": "FILESYSTEMS \"$gpfsMetrics_quota\"",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 14, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "currentFilterKey": "gpfs_fs_name",
     "currentFilterType": "pm_filter",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "metric": "$gpfsMetrics_quota"
    }
   ]
  },
  {
   "title": "Block quotas for \"$byFileset\"",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "filters": [
      {
       "filter": "$byFileset",
       "groupBy": true,
       "tagk": "gpfs_fset_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_rq_blk_hard_limit"
    },
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$byFileset",
       "groupBy": true,
       "tagk": "gpfs_fset_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_rq_blk_soft_limit"
    },
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$byFileset",
       "groupBy": true,
       "tagk": "gpfs_fset_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_rq_blk_current"
    },
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$byFileset",
       "groupBy": true,
       "tagk": "gpfs_fset_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_rq_blk_in_doubt"
    }
   ]
  },
  {
   "title": "File quotas for \"$byFileset\"",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "filters": [
      {
       "filter": "$byFileset",
       "groupBy": true,
       "tagk": "gpfs_fset_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_rq_file_hard_limit"
    },
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$byFileset",
       "groupBy": true,
       "tagk": "gpfs_fset_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_rq_file_soft_limit"
    },
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$byFileset",
       "groupBy": true,
       "tagk": "gpfs_fset_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_rq_file_current"
    },
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$byFileset",
       "groupBy": true,
       "tagk": "gpfs_fset_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_rq_file_in_doubt"
    }
   ]
  }
 ]
}