{
 "title": "File System Capacity View",
 "tags": [
  "default",
  "capacity"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "2h",
 "templating": {
  "list": [
   { "name": "byCluster", "label": "select cluster", "query": "opentsdb" },
   { "name": "gpfsMetrics_disk_cap", "label": "metric1", "query": "metrics(gpfs_disk_)" },
   { "name": "gpfsMetrics_pool_cap", "label": "metric2", "query": "metrics(gpfs_pool_)" },
   { "name": "gpfsMetrics", "label": "metric1", "query": "metrics(gpfs_fs)" },
   {
    "name": "byFsName",
    "query": "tag_values($gpfsMetrics, gpfs_fs_name)"
   },
   { "name": "filterBy", "label": "filterBy", "query": "tag_names($gpfsMetrics)" },
   {
    "name": "values",
    "label": "values",
    "query": "tag_values($gpfsMetrics, $filterBy)"
   },
   {
    "name": "byPoolName",
    "query": "tag_values($gpfsMetrics, gpfs_diskpool_name)"
   },
   {
    "name": "byDisk",
    "query": "tag_values($gpfsMetrics, gpfs_disk_name)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "On this dashboard you can monitor the total or free capacity of ALL mounted file systems from the pool or disk  capacity perspective. \nAlso, you can select one particular filesystem from drop down list *'byFsName'* and observe the capacity of  all  disks  or capacity of pools belonging to the selected file system. \n\n"
   },
   "content": "On this dashboard you can monitor the total or free capacity of ALL mounted file systems from the pool or disk  capacity perspective. \nAlso, you can select one particular filesystem from drop down list *'byFsName'* and observe the capacity of  all  disks  or capacity of pools belonging to the selected file system. \n\n"
  },
  {
   "title": "FILE SYSTEMS \"$gpfsMetrics_disk_cap\"",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "alias": "\"filesystem: [[tag_gpfs_fs_name]]\"",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "",
       "groupBy": true,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      }
     ],
     "metric": "$gpfsMetrics_disk_cap"
    }
   ]
  },
  {
   "title": "FILESYSTEMS \"$gpfsMetrics_pool_cap\"",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "",
       "groupBy": true,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      }
     ],
     "metric": "$gpfsMetrics_pool_cap"
    }
   ]
  },
  {
   "title": "File System \"$byFsName\" Capacity (DISKS)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "filters": [
      {
       "filter": "$byFsName",
       "groupBy": true,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_disk_free_fullkb"
    },
    {
     "aggregator": "sum",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$byFsName",
       "groupBy": true,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_disk_disksize"
    }
   ]
  },
  {
   "title": "FILESYSTEM \"$byFsName\"",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$byFsName",
       "groupBy": true,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_disk_disksize"
    },
    {
     "aggregator": "sum",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$byFsName",
       "groupBy": true,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_disk_free_fragkb"
    },
    {
     "aggregator": "sum",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "filters": [
      {
       "filter": "$byFsName",
       "groupBy": true,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_disk_free_fullkb"
    }
   ]
  },
  {
   "title": "File System \"$byFsName\" Capacity (POOLS)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "filters": [
      {
       "filter": "",
       "groupBy": true,
       "tagk": "gpfs_diskpool_name",
       "type": "pm_filter"
      },
      {
       "filter": "$byFsName",
       "groupBy": true,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_pool_free_dataKB"
    },
    {
     "aggregator": "sum",
     "downsampleAggregator": "sum",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1m",
     "filters": [
      {
       "filter": "$byFsName",
       "groupBy": true,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_pool_total_dataKB"
    }
   ]
  }
 ]
}