{
 "title": "Main Dashbord",
 "tags": [ "main" ],
 "time": { "from": "now/w", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "byCluster", "label": "select cluster", "query": "opentsdb" }
  ]
 },
 "panels": [
  { "title": "DASHBOARD List", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "NODE VIEW Dashboards list", "type": "dashlist", "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 } },
  { "title": "CAPACITY VIEW Dashboards list", "type": "dashlist", "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 } },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "aggregator": "avg", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "cpu_system" },
    { "aggregator": "avg", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "cpu_user" }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    { "aggregator": "avg", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "mem_memtotal" },
    { "aggregator": "avg", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "mem_memfree" },
    { "aggregator": "avg", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "mem_buffers" },
    { "aggregator": "avg", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "mem_cached" }
   ]
  },
  {
   "title": "NETWORK",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "sum",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "5m",
     "metric": "netdev_bytes_r"
    },
    {
     "aggregator": "sum",
     "downsampleAggregator": "sum",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "5m",
     "metric": "netdev_bytes_s"
    }
   ]
  },
  {
   "title": "NSD Server Nodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    { "aggregator": "avg", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "gpfs_nsdds_read_ops" },
    { "aggregator": "avg", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "gpfs_nsdds_write_ops" }
   ]
  },
  {
   "title": "Protocol Nodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    { "aggregator": "avg", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "gpfs_fs_read_ops" },
    { "aggregator": "avg", "downsampleAggregator": "avg", "downsampleFillPolicy": "none", "metric": "gpfs_fs_write_ops" }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } }
 ]
}