{
 "title": "Pool Capacity View",
 "tags": [
  "default",
  "capacity"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "byCluster", "label": "select cluster", "query": "opentsdb" },
   { "name": "gpfsMetrics", "label": "metric1", "query": "metrics(gpfs_)" },
   { "name": "gpfsMetrics1", "label": "metric1", "query": "metrics(gpfs_fs)" },
   { "name": "gpfsMetrics2", "label": "metric1", "query": "metrics(gpfs_disk)" },
   { "name": "gpfsMetrics_disk_cap", "label": "metric1", "query": "metrics(gpfs_disk_)" },
   { "name": "gpfsMetrics_pool_cap", "label": "metric2", "query": "metrics(gpfs_pool_)" },
   { "name": "filterBy", "label": "filterBy", "query": "tag_names($gpfsMetrics)" },
   {
    "name": "byFsName",
    "query": "tag_values($gpfsMetrics1, gpfs_fs_name)"
   },
   {
    "name": "byPoolName",
    "query": "tag_values($gpfsMetrics2, gpfs_diskpool_name)"
   },
   {
    "name": "byDisk",
    "query": "tag_values(gpfs_disk_disksize, gpfs_disk_name)"
   },
   {
    "name": "values",
    "label": "values",
    "query": "tag_values($gpfsMetrics, $filterBy)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "\nOn this dashboard you can monitor the free capacity of the pools and disks.  You can also select pool, disk or filesystem and observe the capacity values for this entity. \nOr you can watch the performance data for  selected disk/pool in combination of one particular disk capacity metric ( *'metric1'*) or pool capacity metric (*'metric2'*).\n\n"
   },
   "content": "\nOn this dashboard you can monitor the free capacity of the pools and disks.  You can also select pool, disk or filesystem and observe the capacity values for this entity. \nOr you can watch the performance data for  selected disk/pool in combination of one particular disk capacity metric ( *'metric1'*) or pool capacity metric (*'metric2'*).\n\n"
  },
  {
   "title": "POOLS Free",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "alias": "\"pool: [[tag_gpfs_diskpool_name]] on filesystem: [[tag_gpfs_fs_name]]\"",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1h",
     "filters": [
      {
       "filter": "",
       "groupBy": true,
       "tagk": "gpfs_diskpool_name",
       "type": "pm_filter"
      },
      {
       "filter": "",
       "groupBy": true,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_pool_free_fullkb"
    }
   ]
  },
  {
   "title": "DISKS Free",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "aggregator": "noop",
     "alias": "\"disk: [[tag_gpfs_disk_name]] in pool: [[tag_gpfs_diskpool_name]]([[tag_gpfs_fs_name]])\"",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "12h",
     "filters": [
      {
       "filter": "",
       "groupBy": true,
       "tagk": "gpfs_disk_name",
       "type": "pm_filter"
      },
      {
       "filter": "",
       "groupBy": true,
       "tagk": "gpfs_diskpool_name",
       "type": "pm_filter"
      },
      {
       "filter": "",
       "groupBy": true,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_disk_free_fullkb"
    }
   ]
  },
  {
   "title": "byFILESYSTEM \"$byFsName\"",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "6h",
     "filters": [
      {
       "filter": "$byFsName",
       "groupBy": true,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_pool_disksize"
    },
    {
     "aggregator": "sum",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "6h",
     "filters": [
      {
       "filter": "$byFsName",
       "groupBy": true,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_pool_free_fragkb"
    },
    {
     "aggregator": "sum",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "6h",
     "filters": [
      {
       "filter": "$byFsName",
       "groupBy": true,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_pool_free_fullkb"
    }
   ]
  },
  {
   "title": "byPOOL \"$byPoolName\"",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1h",
     "filters": [
      {
       "filter": "$byPoolName",
       "groupBy": true,
       "tagk": "gpfs_diskpool_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_pool_disksize"
    },
    {
     "aggregator": "sum",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1h",
     "filters": [
      {
       "filter": "$byPoolName",
       "groupBy": true,
       "tagk": "gpfs_diskpool_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_pool_free_fragkb"
    },
    {
     "aggregator": "sum",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1h",
     "filters": [
      {
       "filter": "$byPoolName",
       "groupBy": true,
       "tagk": "gpfs_diskpool_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_pool_free_fullkb"
    }
   ]
  },
  {
   "title": "byDISK\"$byDisk\"",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "aggregator": "noop",
     "alias": "gpfs_disk_disksize",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1h",
     "filters": [
      {
       "filter": "$byDisk",
       "groupBy": true,
       "tagk": "gpfs_disk_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_disk_disksize"
    },
    {
     "aggregator": "noop",
     "alias": "gpfs_disk_free_fragkb",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1h",
     "filters": [
      {
       "filter": "$byDisk",
       "groupBy": true,
       "tagk": "gpfs_disk_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_disk_free_fragkb"
    },
    {
     "aggregator": "noop",
     "alias": "gpfs_disk_free_fullkb",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1h",
     "filters": [
      {
       "filter": "$byDisk",
       "groupBy": true,
       "tagk": "gpfs_disk_name",
       "type": "pm_filter"
      }
     ],
     "metric": "gpfs_disk_free_fullkb"
    }
   ]
  },
  {
   "title": "byMETRIC1 \"$gpfsMetrics_disk_cap\"",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "kbytes", "label": "GB" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "alias": "\"disk: [[tag_gpfs_disk_name]] in pool: [[tag_gpfs_diskpool_name]]([[tag_gpfs_fs_name]])\"",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "6h",
     "filters": [
      {
       "filter": "",
       "groupBy": true,
       "tagk": "gpfs_diskpool_name",
       "type": "pm_filter"
      },
      {
       "filter": "",
       "groupBy": true,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      },
      {
       "filter": "$byDisk",
       "groupBy": false,
       "tagk": "gpfs_disk_name",
       "type": "pm_filter"
      }
     ],
     "metric": "$gpfsMetrics_disk_cap"
    }
   ]
  },
  {
   "title": "byMETRIC2 \"$gpfsMetrics_pool_cap\"",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "kbytes", "label": "GB" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "alias": "\"pool: [[tag_gpfs_diskpool_name]] on filesystem: [[tag_gpfs_fs_name]]\"",
     "currentFilterType": "literal_or",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "6h",
     "filters": [
      {
       "filter": "",
       "groupBy": true,
       "tagk": "gpfs_fs_name",
       "type": "pm_filter"
      },
      {
       "filter": "$byPoolName",
       "groupBy": true,
       "tagk": "gpfs_diskpool_name",
       "type": "pm_filter"
      }
     ],
     "metric": "$gpfsMetrics_pool_cap"
    }
   ]
  }
 ]
}