{
 "title": "Openshift cluster and IBM Storage Scale cloud native project overview",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "OCP cluster version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cluster_version{type=\"cluster\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Openshift nodes reboots",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(node_boot_time_seconds[24h])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Openshift nodes Health Status",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (condition)\r\n(kube_node_status_condition{status=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Openshift Nodes Health Status",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (condition)\r\n(kube_node_status_condition{status=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Persistent Volume Status Distribution",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (phase) (kube_persistentvolume_status_phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregator": "sum",
     "alias": "$tag_gpfs_cluster_name",
     "downsampleAggregator": "noop",
     "downsampleFillPolicy": "none",
     "expr": "sum by (gpfs_cluster_name)(gpfs_pool_total_metaKB)",
     "legendFormat": "{{gpfs_cluster_name}}"
    }
   ]
  },
  {
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 21, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max by(node) (max_over_time(gpfs_health_status[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Warning events ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gpfs_health_warning_events{gpfs_health_entity=\"-\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error events ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gpfs_health_error_events{gpfs_health_entity=\"-\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filesystems",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "sum by(gpfs_cluster_name, gpfs_fs_name) (gpfs_disk_disksize)",
     "legendFormat": "{{gpfs_fs_name}}"
    }
   ]
  },
  {
   "title": "Disk capacity usage by Filesystem",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 11, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($B-$A)/$B", "type": "math" }
   ]
  },
  {
   "title": "Filesystem READ OPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(gpfs_cluster_name) (gpfs_fs_read_ops)",
     "legendFormat": "{{gpfs_cluster_name}}"
    }
   ]
  },
  {
   "title": "Used disks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "sum by(gpfs_cluster_name, gpfs_disk_name) (gpfs_disk_disksize)",
     "legendFormat": "{{gpfs_fs_name}}"
    }
   ]
  }
 ]
}